[uwsgi]

chmod-socket = 666

# Django-prometheus docs. see https://github.com/django-commons/django-prometheus/blob/d63a6d8803d5d88e4939788192edbebb2de354f0/documentation/exports.md#exporting-metrics-in-a-wsgi-application-with-multiple-processes-per-process
lazy-apps = true

# Log file (debugging)
logto = /var/log/uwsgi.log

# enable master process
master = true

# load a WSGI module
module = centurion_erp.centurion.wsgi:application

# spawn the specified number of workers/processes
processes = 4

# bind to the specified UNIX/TCP socket using default protocol
socket = /run/wsgi.sock

# run each worker in prethreaded mode with the specified number of threads
threads = 2    # Threads per process
