# Generated by Django 5.1.8 on 2025-05-05 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('core', '0022_ticketcommentbase_ticketbase_ticketcommentsolution_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetBaseHistory',
            fields=[
                ('modelhistory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.modelhistory')),
                ('model', models.ForeignKey(help_text='Model this note belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='accounting.assetbase', verbose_name='Model')),
            ],
            options={
                'verbose_name': 'Asset History',
                'verbose_name_plural': 'Asset History',
                'db_table': 'accounting_assetbase_history',
                'ordering': ['-created'],
            },
            bases=('core.modelhistory',),
        ),
    ]
