# Generated by Django 5.1.8 on 2025-05-05 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_assetbasehistory'),
        ('core', '0022_ticketcommentbase_ticketbase_ticketcommentsolution_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetBaseNotes',
            fields=[
                ('modelnotes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.modelnotes')),
                ('model', models.ForeignKey(help_text='Model this note belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='accounting.assetbase', verbose_name='Model')),
            ],
            options={
                'verbose_name': 'Asset Note',
                'verbose_name_plural': 'Asset Notes',
                'db_table': 'accounting_assetbase_notes',
                'ordering': ['-created'],
            },
            bases=('core.modelnotes',),
        ),
    ]
