# Generated by Django 5.1.10 on 2025-07-10 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0002_alter_assetbase_id_alter_assetbase_model_notes_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AssetBaseHistory",
        ),
        migrations.DeleteModel(
            name="AssetBaseNotes",
        ),
    ]
