# Generated by Django 5.1.9 on 2025-05-14 13:48

import access.models.tenancy
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0008_alter_tenant_options_alter_entity_organization_and_more'),
        ('accounting', '0003_assetbasenotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetbase',
            name='organization',
            field=models.ForeignKey(help_text='Tenancy this belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='access.tenant', validators=[access.models.tenancy.TenancyObject.validatate_organization_exists], verbose_name='Tenant'),
        ),
    ]
