# Generated by Django 5.1.15 on 2026-02-25 07:24

import accounting.models.asset_base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_alter_assetbase_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetbase',
            name='asset_type',
            field=models.CharField(blank=True, help_text='Asset Type. (derived from asset model)', max_length=30, validators=[accounting.models.asset_base.AssetBase.validate_not_null], verbose_name='Asset Type'),
        ),
    ]
