# Generated by Django 5.1.15 on 2026-05-30 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_alter_assetbase_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetbase',
            name='asset_type',
        ),
    ]
