# Generated by Django 5.1.15 on 2026-02-25 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_alter_assetbase_asset_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetbase',
            name='asset_type',
        ),
    ]
