ARG CENTURION_IMAGE=ghcr.io/nofusscomputing/centurion-erp

ARG CENTURION_IMAGE_TAG=dev

FROM ${CENTURION_IMAGE}:${CENTURION_IMAGE_TAG}


COPY requirements_dev.txt /requirements_dev.txt

RUN \
    pip install -r /requirements_dev.txt; \
    apk update; \
    apk add --update \
        bash \
        git \
        gcc \
        cmake \
        libc-dev \
        alpine-sdk \
        libffi-dev \
        build-base \
        curl-dev \
        libxml2-dev \
        gettext \
        mariadb-client \
        mariadb-dev \
        pkgconf \
        postgresql16-dev \
        postgresql16-client \
        libpq-dev \
        # NginX: to download items
        openssl \
        curl \
        ca-certificates
