---

variables:
  MY_PROJECT_ID: "57560288"
  GIT_SYNC_URL: "https://$GITHUB_USERNAME_ROBOT:$GITHUB_TOKEN_ROBOT@github.com/NoFussComputing/django_template.git"

  # Docker Build / Publish
  DOCKER_IMAGE_BUILD_TARGET_PLATFORMS: "linux/amd64,linux/arm64"
  DOCKER_IMAGE_BUILD_NAME: django-template
  DOCKER_IMAGE_BUILD_REGISTRY: $CI_REGISTRY_IMAGE
  DOCKER_IMAGE_BUILD_TAG: $CI_COMMIT_SHA

  # Docker Publish
  DOCKER_IMAGE_PUBLISH_NAME: django-template
  DOCKER_IMAGE_PUBLISH_REGISTRY: docker.io/nofusscomputing
  DOCKER_IMAGE_PUBLISH_URL: https://hub.docker.com/r/nofusscomputing/$DOCKER_IMAGE_PUBLISH_NAME

  # Docs NFC
  PAGES_ENVIRONMENT_PATH: projects/django-template/

  # RELEASE_ADDITIONAL_ACTIONS_BUMP: ./.gitlab/additional_actions_bump.sh


include:
  - local: .gitlab/pytest.gitlab-ci.yml
  # - local: .gitlab/unit-test.gitlab-ci.yml
  - project: nofusscomputing/projects/gitlab-ci
    ref: development
    file:
      - .gitlab-ci_common.yaml
      - template/automagic.gitlab-ci.yaml



Docker Container:
  extends: .build_docker_container
  resource_group: build
  needs: []
  rules: # rules manually synced from docker/publish.gitlab-ci.yaml removing git tag

    # - if: # condition_master_branch_push
    #     $CI_COMMIT_BRANCH == "master" && 
    #     $CI_PIPELINE_SOURCE == "push"
    #   exists:
    #     - '{dockerfile,dockerfile.j2}'
    #   when: always

    - if: # condition_dev_branch_push
        (
          $CI_COMMIT_BRANCH == "development"
            ||
          $CI_COMMIT_BRANCH == "master"
        )
         && 
        $CI_PIPELINE_SOURCE == "push"
      exists:
        - '{dockerfile,dockerfile.j2}'
      allow_failure: true
      when: on_success

    - when: never


Docker.Hub.Branch.Publish:
  extends: .publish-docker-hub
  needs: [ "Docker Container" ]
  resource_group: build
  rules: # rules manually synced from docker/publish.gitlab-ci.yaml removing git tag

    # - if: # condition_master_branch_push
    #     $CI_COMMIT_BRANCH == "master" && 
    #     $CI_PIPELINE_SOURCE == "push"
    #   exists:
    #     - '{dockerfile,dockerfile.j2}'
    #   when: always

    - if: # condition_dev_branch_push
        $CI_COMMIT_BRANCH == "development" && 
        $CI_PIPELINE_SOURCE == "push"
      exists:
        - '{dockerfile,dockerfile.j2}'
      allow_failure: true
      when: on_success

    - when: never


Website.Submodule.Deploy:
  extends: .submodule_update_trigger
  variables:
    SUBMODULE_UPDATE_TRIGGER_PROJECT: nofusscomputing/infrastructure/website
  environment:
    url: https://nofusscomputing.com/$PAGES_ENVIRONMENT_PATH
    name: Documentation
  rules:
    - if:  # condition_dev_branch_push
        $CI_COMMIT_BRANCH == "development" && 
        $CI_PIPELINE_SOURCE == "push"
      exists:
        - '{docs/**,pages/**}/*.md'
      changes:
        paths:
          - '{docs/**,pages/**}/*.md'
        compare_to: 'master'
      when: always

    - when: never
