[tool.pylint.main]
disable = [ 
    "all" 
]
enable = [
    "variables"
]
source-roots = [ 
    "app/"
]


[tool.pylint.variables]
allow-global-unused-variables = true
init-import = true



[tool.pytest.ini_options]

addopts = '--cov --cov-branch --cov-report term --tb=long --verbosity=2 --full-trace --showlocals app'


DJANGO_SETTINGS_MODULE = 'app.settings'

junit_family = 'xunit2'
# -- recommended but optional:
# python_files = 'tests.py test_*.py *_tests.py'
log_cli = true
log_cli_level = 'INFO'
log_cli_format = '%(asctime)s %(levelname)s %(message)s'
log_cli_date_format = '%Y-%m-%d %H:%M:%S'

# testpaths = [
#     'tests/*.py',
# #     'tests/functional/**/*.py',
# #     'tests/unit/**/*.py',
# ]
