[tool.pylint.main]
disable = [ 
    "all" 
]
enable = [
    "variables"
]

source-roots = [ 
    "app/"
]


[tool.pylint.variables]
allow-global-unused-variables = true
init-import = true


[tool.pytest.ini_options]
