server {

    listen 8000;

    location = /favicon.ico { access_log off; log_not_found off; }

    location /robots.txt {
        alias /app/static/robots.txt;
    }

    location /static/ {

        alias /data/static/;

    }

    location / {

        include uwsgi_params;

        uwsgi_pass unix:/run/wsgi.sock;

    }

}