server {

    listen 8080;


    location / {

        include uwsgi_params;

        uwsgi_param PATH_INFO /metrics;

        # Required as HTTPS redireect is on.
        uwsgi_param HTTP_X_FORWARDED_PROTO https;

        uwsgi_pass unix:/run/wsgi.sock;

    }
}
