# Generated by Django 5.1.5 on 2025-02-07 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_alter_team_organization_organizationnotes'),
        ('core', '0013_alter_manufacturer_organization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationNotes',
            fields=[
                ('modelnotes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.modelnotes')),
                ('model', models.ForeignKey(help_text='Model this note belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='access.organization', verbose_name='Model')),
            ],
            options={
                'verbose_name': 'Organization Note',
                'verbose_name_plural': 'Organization Notes',
                'db_table': 'access_organization_notes',
                'ordering': ['-created'],
            },
            bases=('core.modelnotes',),
        ),
    ]
