# Generated by Django 5.1.5 on 2025-04-03 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0005_entity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='access.entity')),
                ('f_name', models.CharField(help_text='The persons first name', max_length=64, verbose_name='First Name')),
                ('m_name', models.CharField(blank=True, default=None, help_text='The persons middle name(s)', max_length=100, null=True, verbose_name='Middle Name(s)')),
                ('l_name', models.CharField(help_text='The persons Last name', max_length=64, verbose_name='Last Name')),
                ('dob', models.DateField(blank=True, default=None, help_text='The Persons Date of Birth (DOB)', null=True, verbose_name='DOB')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
                'ordering': ['l_name', 'm_name', 'f_name', 'dob'],
            },
            bases=('access.entity',),
        ),
    ]
