# Generated by Django 5.1.9 on 2025-05-14 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0005_entity_person_entityhistory_entitynotes_role_and_more'),
        ('accounting', '0003_assetbasenotes'),
        ('assistance', '0005_knowledgebasecategoryhistory_knowledgebasehistory'),
        ('config_management', '0007_configgroupshistory_configgrouphostshistory_and_more'),
        ('core', '0025_ticketcommentaction'),
        ('devops', '0011_alter_gitgroup_unique_together_and_more'),
        ('itam', '0011_itamassetbase'),
        ('itim', '0009_slmticket_requestticket'),
        ('project_management', '0005_projecthistory_projectmilestonehistory_and_more'),
        ('settings', '0011_appsettingshistory_externallinkhistory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name = 'Organization',
            new_name = 'Tenant'
        ),
    ]
