# Generated by Django 5.1.5 on 2025-04-03 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0007_contact'),
        ('core', '0020_alter_ticketlinkeditem_item_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityHistory',
            fields=[
                ('modelhistory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.modelhistory')),
                ('model', models.ForeignKey(help_text='Model this note belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='access.entity', verbose_name='Model')),
            ],
            options={
                'verbose_name': 'Entity History',
                'verbose_name_plural': 'Entity History',
                'db_table': 'access_entity_history',
                'ordering': ['-created'],
            },
            bases=('core.modelhistory',),
        ),
    ]
