# Generated by Django 5.1.5 on 2025-04-03 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0008_entityhistory'),
        ('core', '0020_alter_ticketlinkeditem_item_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityNotes',
            fields=[
                ('modelnotes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.modelnotes')),
                ('model', models.ForeignKey(help_text='Model this note belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='access.entity', verbose_name='Model')),
            ],
            options={
                'verbose_name': 'Entity Note',
                'verbose_name_plural': 'Entity Notes',
                'db_table': 'access_entity_notes',
                'ordering': ['-created'],
            },
            bases=('core.modelnotes',),
        ),
    ]
