# Generated by Django 5.1.9 on 2025-05-15 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0009_migrate_organization_permission_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='access.entity')),
                ('name', models.CharField(help_text='The name of this entity', max_length=80, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
                'sub_model_type': 'company',
            },
            bases=('access.entity',),
        ),
    ]
