# Generated by Django 5.2 on 2025-04-06 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0010_role'),
        ('core', '0022_alter_ticketlinkeditem_item_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleNotes',
            fields=[
                ('modelnotes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.modelnotes')),
                ('model', models.ForeignKey(help_text='Model this note belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='access.role', verbose_name='Model')),
            ],
            options={
                'verbose_name': 'Role Note',
                'verbose_name_plural': 'Role Notes',
                'db_table': 'access_role_notes',
                'ordering': ['-created'],
            },
            bases=('core.modelnotes',),
        ),
    ]
