# Generated by Django 5.1.9 on 2025-06-06 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0011_remove_team_is_global_model_notes_and_more"),
        ("core", "0028_delete_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamusers",
            name="model_notes",
            field=models.TextField(
                blank=True,
                help_text="Tid bits of information",
                null=True,
                verbose_name="Notes",
            ),
        ),
        migrations.AlterField(
            model_name="teamusers",
            name="id",
            field=models.AutoField(
                help_text="ID of the item",
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="ID",
            ),
        ),
        migrations.CreateModel(
            name="TeamUsersAuditHistory",
            fields=[
                (
                    "centurionaudit_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.centurionaudit",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        help_text="Model this history belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_history",
                        to="access.teamusers",
                        verbose_name="Model",
                    ),
                ),
            ],
            options={
                "verbose_name": "Team User History",
                "verbose_name_plural": "Team User Histories",
                "db_table": "access_teamusers_audithistory",
                "managed": True,
            },
            bases=("core.centurionaudit", models.Model),
        ),
        migrations.CreateModel(
            name="TeamUsersCenturionModelNote",
            fields=[
                (
                    "centurionmodelnote_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.centurionmodelnote",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        help_text="Model this note belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="access.teamusers",
                        verbose_name="Model",
                    ),
                ),
            ],
            options={
                "verbose_name": "Team User Note",
                "verbose_name_plural": "Team User Notes",
                "db_table": "access_teamusers_centurionmodelnote",
                "managed": True,
            },
            bases=("core.centurionmodelnote", models.Model),
        ),
    ]
