# Generated by Django 5.2 on 2025-04-06 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0011_rolenotes'),
        ('core', '0022_alter_ticketlinkeditem_item_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleHistory',
            fields=[
                ('modelhistory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.modelhistory')),
                ('model', models.ForeignKey(help_text='Model this note belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='access.role', verbose_name='Model')),
            ],
            options={
                'verbose_name': 'Role History',
                'verbose_name_plural': 'Role History',
                'db_table': 'access_role_history',
                'ordering': ['-created'],
            },
            bases=('core.modelhistory',),
        ),
    ]
