# Generated by Django 5.1.9 on 2025-06-06 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0012_teamusers_model_notes_alter_teamusers_id_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TeamUsersAuditHistory",
        ),
    ]
