# Generated by Django 5.1.9 on 2025-06-07 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0013_delete_teamusersaudithistory"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TeamUsersCenturionModelNote",
        ),
    ]
