# Generated by Django 5.1.10 on 2025-08-27 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0014_migrate_teams_to_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(
                help_text="Name of this role", max_length=50, verbose_name="Name"
            ),
        ),
    ]
