# Generated by Django 5.1.9 on 2025-06-07 10:10

import access.models.team
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0014_delete_teamuserscenturionmodelnote"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teamcenturionmodelnote",
            name="centurionmodelnote_ptr",
        ),
        migrations.RemoveField(
            model_name="teamcenturionmodelnote",
            name="model",
        ),
        migrations.RemoveField(
            model_name="teamusers",
            name="model_notes",
        ),
        migrations.AddField(
            model_name="team",
            name="is_global",
            field=models.BooleanField(
                default=False,
                help_text="Is this a global object?",
                verbose_name="Global Object",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="model_notes",
            field=models.TextField(
                blank=True,
                default=None,
                help_text="Tid bits of information",
                null=True,
                verbose_name="Notes",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="organization",
            field=models.ForeignKey(
                help_text="Tenant this belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="access.tenant",
                validators=[access.models.team.Team.validatate_organization_exists],
                verbose_name="Tenant",
            ),
        ),
        migrations.AlterField(
            model_name="teamusers",
            name="id",
            field=models.AutoField(
                help_text="ID of this Team User",
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="ID",
            ),
        ),
        migrations.DeleteModel(
            name="TeamAuditHistory",
        ),
        migrations.DeleteModel(
            name="TeamCenturionModelNote",
        ),
    ]
