# Generated by Django 5.1.10 on 2025-08-27 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0015_alter_role_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TeamHistory",
        ),
        migrations.DeleteModel(
            name="TeamNotes",
        ),
        migrations.DeleteModel(
            name="TeamUsers",
        ),
    ]
