# Generated by Django 5.1.10 on 2025-08-29 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0016_remove_teamnotes_model_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="companyaudithistory",
            options={
                "managed": True,
                "ordering": ["-created"],
                "verbose_name": "Company History",
                "verbose_name_plural": "Company Histories",
            },
        ),
        migrations.AlterModelOptions(
            name="contactaudithistory",
            options={
                "managed": True,
                "ordering": ["-created"],
                "verbose_name": "Contact History",
                "verbose_name_plural": "Contact Histories",
            },
        ),
        migrations.AlterModelOptions(
            name="entityaudithistory",
            options={
                "managed": True,
                "ordering": ["-created"],
                "verbose_name": "Entity History",
                "verbose_name_plural": "Entity Histories",
            },
        ),
        migrations.AlterModelOptions(
            name="personaudithistory",
            options={
                "managed": True,
                "ordering": ["-created"],
                "verbose_name": "Person History",
                "verbose_name_plural": "Person Histories",
            },
        ),
        migrations.AlterModelOptions(
            name="roleaudithistory",
            options={
                "managed": True,
                "ordering": ["-created"],
                "verbose_name": "Role History",
                "verbose_name_plural": "Role Histories",
            },
        ),
        migrations.AlterModelOptions(
            name="tenantaudithistory",
            options={
                "managed": True,
                "ordering": ["-created"],
                "verbose_name": "Tenant History",
                "verbose_name_plural": "Tenant Histories",
            },
        ),
    ]
