# Generated by Django 5.1.10 on 2025-09-27 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0016_companyticket_contactticket_entityticket_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyticket",
            name="model",
            field=models.ForeignKey(
                help_text="Model the ticket is for.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="access.company",
                verbose_name="Model",
            ),
        ),
        migrations.AlterField(
            model_name="contactticket",
            name="model",
            field=models.ForeignKey(
                help_text="Model the ticket is for.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="access.contact",
                verbose_name="Model",
            ),
        ),
        migrations.AlterField(
            model_name="entityticket",
            name="model",
            field=models.ForeignKey(
                help_text="Model the ticket is for.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="access.entity",
                verbose_name="Model",
            ),
        ),
        migrations.AlterField(
            model_name="personticket",
            name="model",
            field=models.ForeignKey(
                help_text="Model the ticket is for.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="access.person",
                verbose_name="Model",
            ),
        ),
        migrations.AlterField(
            model_name="roleticket",
            name="model",
            field=models.ForeignKey(
                help_text="Model the ticket is for.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="access.role",
                verbose_name="Model",
            ),
        ),
        migrations.AlterField(
            model_name="tenantticket",
            name="model",
            field=models.ForeignKey(
                help_text="Model the ticket is for.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="access.tenant",
                verbose_name="Model",
            ),
        ),
    ]
