# Generated by Django 5.1.9 on 2025-06-17 07:27
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0016_remove_tenant_slug_alter_tenant_manager_and_more"),
        ("core", "0033_alter_ticketcommentcategory_parent_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EntityHistory",
        ),
        migrations.DeleteModel(
            name="EntityNotes",
        ),
    ]
