# Generated by Django 5.1.15 on 2026-02-09 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0017_alter_entity_organization_alter_role_organization"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CompanyTicket",
        ),
        migrations.DeleteModel(
            name="ContactTicket",
        ),
        migrations.DeleteModel(
            name="OrganizationHistory",
        ),
        migrations.DeleteModel(
            name="OrganizationNotes",
        ),
        migrations.DeleteModel(
            name="PersonTicket",
        ),
    ]
