# Generated by Django 5.1.14 on 2025-11-19 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0017_alter_entity_organization_alter_role_organization"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CompanyTicket",
        ),
        migrations.DeleteModel(
            name="ContactTicket",
        ),
        migrations.DeleteModel(
            name="PersonTicket",
        ),
    ]
