# Generated by Django 5.1.15 on 2026-02-25 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0018_remove_contactticket_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='entity_type',
        ),
    ]
