# Generated by Django 5.1.10 on 2025-07-06 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0018_remove_entity_is_global_alter_entity_id_and_more"),
        ("core", "0033_alter_ticketcommentcategory_parent_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyAuditHistory",
            fields=[
                (
                    "centurionaudit_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.centurionaudit",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        help_text="Model this history belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="access.company",
                        verbose_name="Model",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company History",
                "verbose_name_plural": "Company Histories",
                "db_table": "access_company_audithistory",
                "managed": True,
            },
            bases=("core.centurionaudit",),
        ),
        migrations.CreateModel(
            name="CompanyCenturionModelNote",
            fields=[
                (
                    "centurionmodelnote_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.centurionmodelnote",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        help_text="Model this note belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="access.company",
                        verbose_name="Model",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Note",
                "verbose_name_plural": "Company Notes",
                "db_table": "access_company_centurionmodelnote",
                "managed": True,
            },
            bases=("core.centurionmodelnote",),
        ),
    ]
