# Generated by Django 5.1.15 on 2025-12-09 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0018_remove_contactticket_model_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OrganizationHistory",
        ),
        migrations.DeleteModel(
            name="OrganizationNotes",
        ),
    ]
