# Generated by Django 5.1.10 on 2025-07-12 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0020_remove_rolenotes_model_and_more"),
        ("core", "0033_alter_ticketcommentcategory_parent_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoleAuditHistory",
            fields=[
                (
                    "centurionaudit_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.centurionaudit",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        help_text="Model this history belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_history",
                        to="access.role",
                        verbose_name="Model",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role History",
                "verbose_name_plural": "Role Histories",
                "db_table": "access_role_audithistory",
                "managed": True,
            },
            bases=("core.centurionaudit",),
        ),
        migrations.CreateModel(
            name="RoleCenturionModelNote",
            fields=[
                (
                    "centurionmodelnote_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.centurionmodelnote",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        help_text="Model this note belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="access.role",
                        verbose_name="Model",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role Note",
                "verbose_name_plural": "Role Notes",
                "db_table": "access_role_centurionmodelnote",
                "managed": True,
            },
            bases=("core.centurionmodelnote",),
        ),
    ]
