# Generated by Django 5.1.5 on 2025-02-07 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_manufacturer_organization_and_more'),
        ('itam', '0008_alter_device_organization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceNotes',
            fields=[
                ('modelnotes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.modelnotes')),
                ('model', models.ForeignKey(help_text='Model this note belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='itam.device', verbose_name='Model')),
            ],
            options={
                'verbose_name': 'Device Note',
                'verbose_name_plural': 'Device Notes',
                'db_table': 'itam_device_notes',
                'ordering': ['-created'],
            },
            bases=('core.modelnotes',),
        ),
    ]
