# Generated by Django 5.1.5 on 2025-02-15 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_modelhistory'),
        ('itam', '0008_alter_device_organization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceHistory',
            fields=[
                ('modelhistory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.modelhistory')),
                ('model', models.ForeignKey(help_text='Model this note belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='itam.device', verbose_name='Model')),
            ],
            options={
                'verbose_name': 'Device History',
                'verbose_name_plural': 'Device History',
                'db_table': 'itam_device_history',
                'ordering': ['-created'],
            },
            bases=('core.modelhistory',),
        ),
    ]
