# Generated by Django 5.1.5 on 2025-02-15 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itam', '0009_devicehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceSoftwareHistory',
            fields=[
                ('devicehistory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='itam.devicehistory')),
                ('child_model', models.ForeignKey(help_text='Model this note belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='itam.devicesoftware', verbose_name='Model')),
            ],
            options={
                'verbose_name': 'Device Software History',
                'verbose_name_plural': 'Device Software History',
                'db_table': 'itam_device_software_history',
                'ordering': ['-created'],
            },
            bases=('itam.devicehistory',),
        ),
    ]
