# Generated by Django 5.1.10 on 2025-09-23 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_modelticket_manufacturerticket_ticketcategoryticket_and_more"),
        ("itam", "0013_alter_deviceaudithistory_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceModelTicket",
            fields=[
                (
                    "modelticket_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.modelticket",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        help_text="Ticket this Model belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="itam.devicemodel",
                        verbose_name="Ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Device Model Ticket",
                "verbose_name_plural": "Device Model Tickets",
                "db_table": "itam_devicemodel_ticket",
                "managed": True,
            },
            bases=("core.modelticket",),
        ),
        migrations.CreateModel(
            name="DeviceTicket",
            fields=[
                (
                    "modelticket_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.modelticket",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        help_text="Ticket this Model belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="itam.device",
                        verbose_name="Ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Device Ticket",
                "verbose_name_plural": "Device Tickets",
                "db_table": "itam_device_ticket",
                "managed": True,
            },
            bases=("core.modelticket",),
        ),
        migrations.CreateModel(
            name="DeviceTypeTicket",
            fields=[
                (
                    "modelticket_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.modelticket",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        help_text="Ticket this Model belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="itam.devicetype",
                        verbose_name="Ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Device Type Ticket",
                "verbose_name_plural": "Device Type Tickets",
                "db_table": "itam_devicetype_ticket",
                "managed": True,
            },
            bases=("core.modelticket",),
        ),
        migrations.CreateModel(
            name="ITAMAssetBaseTicket",
            fields=[
                (
                    "modelticket_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.modelticket",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        help_text="Ticket this Model belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="itam.itamassetbase",
                        verbose_name="Ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "IT Asset Ticket",
                "verbose_name_plural": "IT Asset Tickets",
                "db_table": "itam_itamassetbase_ticket",
                "managed": True,
            },
            bases=("core.modelticket",),
        ),
        migrations.CreateModel(
            name="OperatingSystemTicket",
            fields=[
                (
                    "modelticket_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.modelticket",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        help_text="Ticket this Model belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="itam.operatingsystem",
                        verbose_name="Ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Operating System Ticket",
                "verbose_name_plural": "Operating System Tickets",
                "db_table": "itam_operatingsystem_ticket",
                "managed": True,
            },
            bases=("core.modelticket",),
        ),
        migrations.CreateModel(
            name="OperatingSystemVersionTicket",
            fields=[
                (
                    "modelticket_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.modelticket",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        help_text="Ticket this Model belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="itam.operatingsystemversion",
                        verbose_name="Ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Operating System Version Ticket",
                "verbose_name_plural": "Operating System Version Tickets",
                "db_table": "itam_operatingsystemversion_ticket",
                "managed": True,
            },
            bases=("core.modelticket",),
        ),
        migrations.CreateModel(
            name="SoftwareCategoryTicket",
            fields=[
                (
                    "modelticket_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.modelticket",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        help_text="Ticket this Model belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="itam.softwarecategory",
                        verbose_name="Ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Software Category Ticket",
                "verbose_name_plural": "Software Category Tickets",
                "db_table": "itam_softwarecategory_ticket",
                "managed": True,
            },
            bases=("core.modelticket",),
        ),
        migrations.CreateModel(
            name="SoftwareTicket",
            fields=[
                (
                    "modelticket_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.modelticket",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        help_text="Ticket this Model belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="itam.software",
                        verbose_name="Ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Software Ticket",
                "verbose_name_plural": "Software Tickets",
                "db_table": "itam_software_ticket",
                "managed": True,
            },
            bases=("core.modelticket",),
        ),
        migrations.CreateModel(
            name="SoftwareVersionTicket",
            fields=[
                (
                    "modelticket_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.modelticket",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        help_text="Ticket this Model belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="itam.softwareversion",
                        verbose_name="Ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Software Version Ticket",
                "verbose_name_plural": "Software Version Tickets",
                "db_table": "itam_softwareversion_ticket",
                "managed": True,
            },
            bases=("core.modelticket",),
        ),
    ]
