# Generated by Django 5.1.10 on 2025-09-27 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("itam", "0014_devicemodelticket_deviceticket_devicetypeticket_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicemodelticket",
            name="model",
            field=models.ForeignKey(
                help_text="Model the ticket is for.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="itam.devicemodel",
                verbose_name="Model",
            ),
        ),
        migrations.AlterField(
            model_name="deviceticket",
            name="model",
            field=models.ForeignKey(
                help_text="Model the ticket is for.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="itam.device",
                verbose_name="Model",
            ),
        ),
        migrations.AlterField(
            model_name="devicetypeticket",
            name="model",
            field=models.ForeignKey(
                help_text="Model the ticket is for.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="itam.devicetype",
                verbose_name="Model",
            ),
        ),
        migrations.AlterField(
            model_name="itamassetbaseticket",
            name="model",
            field=models.ForeignKey(
                help_text="Model the ticket is for.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="itam.itamassetbase",
                verbose_name="Model",
            ),
        ),
        migrations.AlterField(
            model_name="operatingsystemticket",
            name="model",
            field=models.ForeignKey(
                help_text="Model the ticket is for.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="itam.operatingsystem",
                verbose_name="Model",
            ),
        ),
        migrations.AlterField(
            model_name="operatingsystemversionticket",
            name="model",
            field=models.ForeignKey(
                help_text="Model the ticket is for.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="itam.operatingsystemversion",
                verbose_name="Model",
            ),
        ),
        migrations.AlterField(
            model_name="softwarecategoryticket",
            name="model",
            field=models.ForeignKey(
                help_text="Model the ticket is for.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="itam.softwarecategory",
                verbose_name="Model",
            ),
        ),
        migrations.AlterField(
            model_name="softwareticket",
            name="model",
            field=models.ForeignKey(
                help_text="Model the ticket is for.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="itam.software",
                verbose_name="Model",
            ),
        ),
        migrations.AlterField(
            model_name="softwareversionticket",
            name="model",
            field=models.ForeignKey(
                help_text="Model the ticket is for.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="itam.softwareversion",
                verbose_name="Model",
            ),
        ),
    ]
