# Generated by Django 5.1.9 on 2025-06-08 05:12

import django.db.models.deletion
import itam.models.device
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("itam", "0014_remove_device_is_global_remove_device_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="config",
            field=models.JSONField(
                blank=True,
                help_text="Configuration for this device",
                null=True,
                validators=[
                    itam.models.device.Device.validate_config_keys_not_reserved
                ],
                verbose_name="Host Configuration",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="device_model",
            field=models.ForeignKey(
                blank=True,
                help_text="Model of the device.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="itam.devicemodel",
                verbose_name="Model",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="device_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Type of device.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="itam.devicetype",
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="serial_number",
            field=models.CharField(
                blank=True,
                help_text="Serial number of the device.",
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Serial Number",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="uuid",
            field=models.UUIDField(
                blank=True,
                help_text="System GUID/UUID.",
                null=True,
                unique=True,
                validators=[itam.models.device.Device.validate_uuid_format],
                verbose_name="UUID",
            ),
        ),
    ]
