# Generated by Django 5.1.9 on 2025-06-11 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_alter_ticketcommentcategory_parent_and_more"),
        ("itam", "0015_alter_device_config_alter_device_device_model_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicemodel",
            name="manufacturer",
            field=models.ForeignKey(
                blank=True,
                help_text="Manufacturer this model is from",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.manufacturer",
                verbose_name="Manufacturer",
            ),
        ),
    ]
