# Generated by Django 5.1.5 on 2025-02-07 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_manufacturernotes'),
        ('itam', '0015_softwarecategorynotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareVersionNotes',
            fields=[
                ('modelnotes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.modelnotes')),
                ('model', models.ForeignKey(help_text='Model this note belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='itam.softwareversion', verbose_name='Model')),
            ],
            options={
                'verbose_name': 'Software Version Note',
                'verbose_name_plural': 'Software Version Notes',
                'db_table': 'itam_software_version_notes',
                'ordering': ['-created'],
            },
            bases=('core.modelnotes',),
        ),
    ]
