# Generated by Django 5.1.13 on 2025-10-21 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("itam", "0016_alter_software_organization"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="devicemodel",
            options={
                "ordering": ["manufacturer_old", "name"],
                "verbose_name": "Device Model",
                "verbose_name_plural": "Device Models",
            },
        ),
        migrations.AlterModelOptions(
            name="software",
            options={
                "ordering": ["name", "publisher_old__name"],
                "verbose_name": "Software",
                "verbose_name_plural": "Softwares",
            },
        ),
        migrations.RenameField(
            model_name="devicemodel",
            old_name="manufacturer",
            new_name="manufacturer_old",
        ),
        migrations.RenameField(
            model_name="operatingsystem",
            old_name="publisher",
            new_name="publisher_old",
        ),
        migrations.RenameField(
            model_name="software",
            old_name="publisher",
            new_name="publisher_old",
        ),
    ]
