# Generated by Django 5.1.13 on 2025-10-21 03:47
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("itam", "0016_alter_software_organization"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="devicemodel",
            options={
                "ordering": ["manufacturer_old", "name"],
                "verbose_name": "Device Model",
                "verbose_name_plural": "Device Models",
            },
        ),
        migrations.AlterModelOptions(
            name="software",
            options={
                "ordering": ["name", "publisher_old__name"],
                "verbose_name": "Software",
                "verbose_name_plural": "Softwares",
            },
        ),
        migrations.RenameField(
            model_name="devicemodel",
            old_name="manufacturer",
            new_name="manufacturer_old",
        ),
        migrations.RenameField(
            model_name="operatingsystem",
            old_name="publisher",
            new_name="publisher_old",
        ),
        migrations.RenameField(
            model_name="software",
            old_name="publisher",
            new_name="publisher_old",
        ),
        migrations.AlterField(
            model_name="devicemodel",
            name="manufacturer_old",
            field=models.ForeignKey(
                blank=True,
                help_text="Manufacturer this model is from",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.manufacturer",
                verbose_name="Manufacturer",
            ),
        ),
        migrations.AlterField(
            model_name="operatingsystem",
            name="publisher_old",
            field=models.ForeignKey(
                blank=True,
                help_text="Who publishes this Operating System",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.manufacturer",
                verbose_name="Publisher",
            ),
        ),
        migrations.AlterField(
            model_name="software",
            name="publisher_old",
            field=models.ForeignKey(
                blank=True,
                help_text="Who publishes this software",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.manufacturer",
                verbose_name="Publisher",
            ),
        ),
    ]
