# Generated by Django 5.1.5 on 2025-02-17 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itam', '0018_softwareversionhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicesoftwarehistory',
            name='child_model',
            field=models.ForeignKey(help_text='Model this note belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='itam.devicesoftware', verbose_name='Model'),
        ),
    ]
