# Generated by Django 5.1.14 on 2025-11-19 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("itam", "0019_alter_devicemodel_options_alter_software_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ITAMAssetBaseTicket",
        ),
    ]
