# Generated by Django 5.1.15 on 2026-02-09 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("itam", "0019_alter_devicemodel_options_alter_software_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DeviceHistory",
        ),
        migrations.DeleteModel(
            name="DeviceModelHistory",
        ),
        migrations.DeleteModel(
            name="DeviceModelNotes",
        ),
        migrations.DeleteModel(
            name="DeviceNotes",
        ),
        migrations.DeleteModel(
            name="DeviceOperatingSystemHistory",
        ),
        migrations.DeleteModel(
            name="DeviceSoftwareHistory",
        ),
        migrations.DeleteModel(
            name="DeviceTypeHistory",
        ),
        migrations.DeleteModel(
            name="DeviceTypeNotes",
        ),
        migrations.DeleteModel(
            name="ITAMAssetBaseTicket",
        ),
        migrations.DeleteModel(
            name="OperatingSystemHistory",
        ),
        migrations.DeleteModel(
            name="OperatingSystemNotes",
        ),
        migrations.DeleteModel(
            name="OperatingSystemVersionHistory",
        ),
        migrations.DeleteModel(
            name="OperatingSystemVersionNotes",
        ),
        migrations.DeleteModel(
            name="SoftwareCategoryHistory",
        ),
        migrations.DeleteModel(
            name="SoftwareCategoryNotes",
        ),
        migrations.DeleteModel(
            name="SoftwareHistory",
        ),
        migrations.DeleteModel(
            name="SoftwareNotes",
        ),
        migrations.DeleteModel(
            name="SoftwareVersionHistory",
        ),
        migrations.DeleteModel(
            name="SoftwareVersionNotes",
        ),
    ]
