# Generated by Django 5.1.15 on 2026-02-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itam', '0020_remove_devicesoftwarehistory_devicehistory_ptr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itamassetbase',
            name='itam_type',
            field=models.CharField(blank=True, help_text='IT Asset Type. (derived from IT asset model)', max_length=30, verbose_name='IT Asset Type'),
        ),
    ]
