# Generated by Django 5.1.15 on 2026-05-30 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itam', '0020_remove_devicesoftwarehistory_devicehistory_ptr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itamassetbase',
            name='itam_type',
        ),
    ]
