# Generated by Django 5.1.15 on 2025-12-09 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("itam", "0020_delete_itamassetbaseticket"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DeviceHistory",
        ),
        migrations.DeleteModel(
            name="DeviceModelHistory",
        ),
        migrations.DeleteModel(
            name="DeviceOperatingSystemHistory",
        ),
        migrations.DeleteModel(
            name="DeviceSoftwareHistory",
        ),
        migrations.DeleteModel(
            name="DeviceTypeHistory",
        ),
        migrations.DeleteModel(
            name="OperatingSystemHistory",
        ),
        migrations.DeleteModel(
            name="OperatingSystemVersionHistory",
        ),
        migrations.DeleteModel(
            name="SoftwareCategoryHistory",
        ),
        migrations.DeleteModel(
            name="SoftwareHistory",
        ),
        migrations.DeleteModel(
            name="SoftwareVersionHistory",
        ),
    ]
