# Generated by Django 5.1.9 on 2025-06-12 02:42

import access.models.tenancy_abstract
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0016_remove_tenant_slug_alter_tenant_manager_and_more"),
        ("core", "0033_alter_ticketcommentcategory_parent_and_more"),
        ("itam", "0021_remove_software_is_global_remove_software_slug_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="softwarecategory",
            name="is_global",
        ),
        migrations.RemoveField(
            model_name="softwarecategory",
            name="slug",
        ),
        migrations.AlterField(
            model_name="softwarecategory",
            name="id",
            field=models.AutoField(
                help_text="ID of the item",
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="softwarecategory",
            name="model_notes",
            field=models.TextField(
                blank=True,
                help_text="Tid bits of information",
                null=True,
                verbose_name="Notes",
            ),
        ),
        migrations.AlterField(
            model_name="softwarecategory",
            name="organization",
            field=models.ForeignKey(
                help_text="Tenant this belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="access.tenant",
                validators=[
                    access.models.tenancy_abstract.TenancyAbstractModel.validatate_organization_exists
                ],
                verbose_name="Tenant",
            ),
        ),
        migrations.CreateModel(
            name="SoftwareCategoryAuditHistory",
            fields=[
                (
                    "centurionaudit_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.centurionaudit",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        help_text="Model this history belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_history",
                        to="itam.softwarecategory",
                        verbose_name="Model",
                    ),
                ),
            ],
            options={
                "verbose_name": "Software Category History",
                "verbose_name_plural": "Software Category Histories",
                "db_table": "itam_softwarecategory_audithistory",
                "managed": True,
            },
            bases=("core.centurionaudit",),
        ),
        migrations.CreateModel(
            name="SoftwareCategoryCenturionModelNote",
            fields=[
                (
                    "centurionmodelnote_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.centurionmodelnote",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        help_text="Model this note belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="itam.softwarecategory",
                        verbose_name="Model",
                    ),
                ),
            ],
            options={
                "verbose_name": "Software Category Note",
                "verbose_name_plural": "Software Category Notes",
                "db_table": "itam_softwarecategory_centurionmodelnote",
                "managed": True,
            },
            bases=("core.centurionmodelnote",),
        ),
    ]
