# Generated by Django 5.1.15 on 2026-02-25 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itam', '0021_alter_itamassetbase_itam_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itamassetbase',
            name='itam_type',
        ),
    ]
