# Generated by Django 5.1.15 on 2025-12-09 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("itam", "0021_remove_deviceoperatingsystemhistory_devicehistory_ptr_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DeviceModelNotes",
        ),
        migrations.DeleteModel(
            name="DeviceNotes",
        ),
        migrations.DeleteModel(
            name="DeviceTypeNotes",
        ),
        migrations.DeleteModel(
            name="OperatingSystemNotes",
        ),
        migrations.DeleteModel(
            name="OperatingSystemVersionNotes",
        ),
        migrations.DeleteModel(
            name="SoftwareCategoryNotes",
        ),
        migrations.DeleteModel(
            name="SoftwareNotes",
        ),
        migrations.DeleteModel(
            name="SoftwareVersionNotes",
        ),
    ]
