# Generated by Django 5.1.10 on 2025-07-10 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_alter_ticketcommentcategory_parent_and_more"),
        ("itam", "0024_alter_software_organization"),
    ]

    operations = [
        migrations.CreateModel(
            name="ITAMAssetBaseAuditHistory",
            fields=[
                (
                    "centurionaudit_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.centurionaudit",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        help_text="Model this history belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="itam.itamassetbase",
                        verbose_name="Model",
                    ),
                ),
            ],
            options={
                "verbose_name": "IT Asset History",
                "verbose_name_plural": "IT Asset Histories",
                "db_table": "itam_itamassetbase_audithistory",
                "managed": True,
            },
            bases=("core.centurionaudit",),
        ),
        migrations.CreateModel(
            name="ITAMAssetBaseCenturionModelNote",
            fields=[
                (
                    "centurionmodelnote_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.centurionmodelnote",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        help_text="Model this note belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="itam.itamassetbase",
                        verbose_name="Model",
                    ),
                ),
            ],
            options={
                "verbose_name": "IT Asset Note",
                "verbose_name_plural": "IT Asset Notes",
                "db_table": "itam_itamassetbase_centurionmodelnote",
                "managed": True,
            },
            bases=("core.centurionmodelnote",),
        ),
    ]
