# Generated by Django 5.1.5 on 2025-02-17 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_management', '0007_configgroupshistory_configgrouphostshistory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configgrouphostshistory',
            name='child_model',
            field=models.ForeignKey(help_text='Model this note belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='config_management.configgrouphosts', verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='configgroupsoftwarehistory',
            name='child_model',
            field=models.ForeignKey(help_text='Model this note belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='config_management.configgroupsoftware', verbose_name='Model'),
        ),
    ]
