# Generated by Django 5.1.9 on 2025-06-06 02:42

import access.models.tenancy_abstract
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0012_teamusers_model_notes_alter_teamusers_id_and_more"),
        ("config_management", "0009_remove_configgroups_is_global_and_more"),
        ("core", "0028_delete_history"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="configgrouphosts",
            name="is_global",
        ),
        migrations.AlterField(
            model_name="configgrouphosts",
            name="id",
            field=models.AutoField(
                help_text="ID of the item",
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="configgrouphosts",
            name="model_notes",
            field=models.TextField(
                blank=True,
                help_text="Tid bits of information",
                null=True,
                verbose_name="Notes",
            ),
        ),
        migrations.AlterField(
            model_name="configgrouphosts",
            name="organization",
            field=models.ForeignKey(
                help_text="Tenant this belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="access.tenant",
                validators=[
                    access.models.tenancy_abstract.TenancyAbstractModel.validatate_organization_exists
                ],
                verbose_name="Tenant",
            ),
        ),
        migrations.CreateModel(
            name="ConfigGroupHostsAuditHistory",
            fields=[
                (
                    "centurionaudit_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.centurionaudit",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        help_text="Model this history belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_history",
                        to="config_management.configgrouphosts",
                        verbose_name="Model",
                    ),
                ),
            ],
            options={
                "verbose_name": "config group hosts History",
                "verbose_name_plural": "config group hosts Histories",
                "db_table": "config_management_configgrouphosts_audithistory",
                "managed": True,
            },
            bases=("core.centurionaudit", models.Model),
        ),
        migrations.CreateModel(
            name="ConfigGroupHostsCenturionModelNote",
            fields=[
                (
                    "centurionmodelnote_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.centurionmodelnote",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        help_text="Model this note belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="config_management.configgrouphosts",
                        verbose_name="Model",
                    ),
                ),
            ],
            options={
                "verbose_name": "config group hosts Note",
                "verbose_name_plural": "config group hosts Notes",
                "db_table": "config_management_configgrouphosts_centurionmodelnote",
                "managed": True,
            },
            bases=("core.centurionmodelnote", models.Model),
        )
    ]
