# Generated by Django 5.1.9 on 2025-06-07 03:57

import config_management.models.groups
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config_management", "0011_remove_configgroupsoftware_is_global_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configgroups",
            name="config",
            field=models.JSONField(
                blank=True,
                help_text="Configuration for this Group",
                null=True,
                validators=[
                    config_management.models.groups.ConfigGroups.validate_config_keys_not_reserved
                ],
                verbose_name="Configuration",
            ),
        ),
        migrations.AlterField(
            model_name="configgroups",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent of this Group",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="config_management.configgroups",
                verbose_name="Parent Group",
            ),
        ),
    ]
