# Generated by Django 5.1.9 on 2025-06-07 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "config_management",
            "0012_alter_configgroups_config_alter_configgroups_parent",
        ),
        ("itam", "0014_remove_device_is_global_remove_device_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configgroupsoftware",
            name="action",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Install"), (0, "Remove")],
                help_text="ACtion to perform with this software",
                null=True,
                verbose_name="Action",
            ),
        ),
        migrations.AlterField(
            model_name="configgroupsoftware",
            name="config_group",
            field=models.ForeignKey(
                help_text="Config group this softwre will be linked to",
                on_delete=django.db.models.deletion.PROTECT,
                to="config_management.configgroups",
                verbose_name="Config Group",
            ),
        ),
        migrations.AlterField(
            model_name="configgroupsoftware",
            name="software",
            field=models.ForeignKey(
                help_text="Software to add to this config Group",
                on_delete=django.db.models.deletion.PROTECT,
                to="itam.software",
                verbose_name="Software",
            ),
        ),
        migrations.AlterField(
            model_name="configgroupsoftware",
            name="version",
            field=models.ForeignKey(
                blank=True,
                help_text="Software Version for this config group",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="itam.softwareversion",
                verbose_name="Verrsion",
            ),
        ),
    ]
