# Generated by Django 5.1.15 on 2025-12-09 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("config_management", "0012_alter_configgrouphosts_organization_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ConfigGroupHostsHistory",
        ),
        migrations.DeleteModel(
            name="ConfigGroupsHistory",
        ),
        migrations.DeleteModel(
            name="ConfigGroupSoftwareHistory",
        ),
    ]
