# Generated by Django 5.1.9 on 2025-06-07 04:11

import config_management.models.groups
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config_management", "0013_alter_configgroupsoftware_action_and_more"),
        ("itam", "0014_remove_device_is_global_remove_device_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configgrouphosts",
            name="group",
            field=models.ForeignKey(
                help_text="Group that this host is part of",
                on_delete=django.db.models.deletion.PROTECT,
                to="config_management.configgroups",
                verbose_name="Group",
            ),
        ),
        migrations.AlterField(
            model_name="configgrouphosts",
            name="host",
            field=models.ForeignKey(
                help_text="Host that will be apart of this config group",
                on_delete=django.db.models.deletion.PROTECT,
                to="itam.device",
                validators=[
                    config_management.models.groups.ConfigGroupHosts.validate_host_no_parent_group
                ],
                verbose_name="Host",
            ),
        ),
    ]
