# Generated by Django 5.1.9 on 2025-06-07 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("config_management", "0014_alter_configgrouphosts_group_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="configgroupsoftwarecenturionmodelnote",
            name="centurionmodelnote_ptr",
        ),
        migrations.RemoveField(
            model_name="configgroupsoftwarecenturionmodelnote",
            name="model",
        ),
        migrations.DeleteModel(
            name="ConfigGroupHostsCenturionModelNote",
        ),
        migrations.DeleteModel(
            name="ConfigGroupSoftwareCenturionModelNote",
        ),
    ]
