# Generated by Django 5.1.5 on 2025-02-16 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_ticketcommentcategoryhistory'),
        ('project_management', '0004_projectmilestonenotes_projectnotes_projectstatenotes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectHistory',
            fields=[
                ('modelhistory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.modelhistory')),
                ('model', models.ForeignKey(help_text='Model this note belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='project_management.project', verbose_name='Model')),
            ],
            options={
                'verbose_name': 'Project History',
                'verbose_name_plural': 'Project History',
                'db_table': 'project_management_project_history',
                'ordering': ['-created'],
            },
            bases=('core.modelhistory',),
        ),
    ]
