# Generated by Django 5.1.5 on 2025-02-16 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0005_projecthistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMilestoneHistory',
            fields=[
                ('projecthistory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='project_management.projecthistory')),
                ('child_model', models.ForeignKey(help_text='Model this note belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='project_management.projectmilestone', verbose_name='Model')),
            ],
            options={
                'verbose_name': 'Project Milestone History',
                'verbose_name_plural': 'Project Milestone History',
                'db_table': 'project_management_projectmilestone_history',
                'ordering': ['-created'],
            },
            bases=('project_management.projecthistory',),
        ),
    ]
