# Generated by Django 5.1.9 on 2025-05-17 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_rename_manufacturerhistory_manufactureraudithistory'),
        ('project_management', '0006_alter_project_organization_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectHistory',
            new_name='ProjectAuditHistory',
        ),
        migrations.RenameModel(
            old_name='ProjectMilestoneHistory',
            new_name='ProjectMilestoneAuditHistory',
        ),
        migrations.RenameModel(
            old_name='ProjectStateHistory',
            new_name='ProjectStateAuditHistory',
        ),
        migrations.RenameModel(
            old_name='ProjectTypeHistory',
            new_name='ProjectTypeAuditHistory',
        ),
    ]
