# Generated by Django 5.1.9 on 2025-06-14 03:23

import access.models.tenancy_abstract
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0016_remove_tenant_slug_alter_tenant_manager_and_more"),
        ("core", "0033_alter_ticketcommentcategory_parent_and_more"),
        (
            "project_management",
            "0007_remove_project_is_global_remove_project_slug_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectmilestone",
            name="is_global",
        ),
        migrations.RemoveField(
            model_name="projectmilestone",
            name="slug",
        ),
        migrations.AlterField(
            model_name="projectmilestone",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Description of milestone. Markdown supported",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="projectmilestone",
            name="id",
            field=models.AutoField(
                help_text="ID of the item",
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="projectmilestone",
            name="organization",
            field=models.ForeignKey(
                help_text="Tenant this belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="access.tenant",
                validators=[
                    access.models.tenancy_abstract.TenancyAbstractModel.validatate_organization_exists
                ],
                verbose_name="Tenant",
            ),
        ),
        migrations.CreateModel(
            name="ProjectMilestoneAuditHistory",
            fields=[
                (
                    "centurionaudit_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.centurionaudit",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        help_text="Model this history belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_history",
                        to="project_management.projectmilestone",
                        verbose_name="Model",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Milestone History",
                "verbose_name_plural": "Project Milestone Histories",
                "db_table": "project_management_projectmilestone_audithistory",
                "managed": True,
            },
            bases=("core.centurionaudit",),
        ),
        migrations.CreateModel(
            name="ProjectMilestoneCenturionModelNote",
            fields=[
                (
                    "centurionmodelnote_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.centurionmodelnote",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        help_text="Model this note belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="project_management.projectmilestone",
                        verbose_name="Model",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Milestone Note",
                "verbose_name_plural": "Project Milestone Notes",
                "db_table": "project_management_projectmilestone_centurionmodelnote",
                "managed": True,
            },
            bases=("core.centurionmodelnote",),
        ),
    ]
