# Generated by Django 5.1.10 on 2025-08-23 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        (
            "project_management",
            "0007_remove_project_is_global_remove_project_slug_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="manager_team",
            field=models.ForeignKey(
                blank=True,
                help_text="Group which contains the Project Managers",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="auth.group",
                verbose_name="Project Manager Group",
            ),
        ),
    ]
