# Generated by Django 5.1.5 on 2025-02-16 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_ticketcommentcategoryhistory'),
        ('project_management', '0007_projectstatehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTypeHistory',
            fields=[
                ('modelhistory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.modelhistory')),
                ('model', models.ForeignKey(help_text='Model this note belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='project_management.projecttype', verbose_name='Model')),
            ],
            options={
                'verbose_name': 'Project Type History',
                'verbose_name_plural': 'Project Type History',
                'db_table': 'project_management_projecttype_history',
                'ordering': ['-created'],
            },
            bases=('core.modelhistory',),
        ),
    ]
