# Generated by Django 5.1.10 on 2025-08-29 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project_management", "0008_alter_project_manager_team"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectaudithistory",
            options={
                "managed": True,
                "ordering": ["-created"],
                "verbose_name": "Project History",
                "verbose_name_plural": "Project Histories",
            },
        ),
        migrations.AlterModelOptions(
            name="projectmilestoneaudithistory",
            options={
                "managed": True,
                "ordering": ["-created"],
                "verbose_name": "Project Milestone History",
                "verbose_name_plural": "Project Milestone Histories",
            },
        ),
        migrations.AlterModelOptions(
            name="projectstateaudithistory",
            options={
                "managed": True,
                "ordering": ["-created"],
                "verbose_name": "Project State History",
                "verbose_name_plural": "Project State Histories",
            },
        ),
        migrations.AlterModelOptions(
            name="projecttypeaudithistory",
            options={
                "managed": True,
                "ordering": ["-created"],
                "verbose_name": "Project Type History",
                "verbose_name_plural": "Project Type Histories",
            },
        ),
    ]
