# Generated by Django 5.1.10 on 2025-09-23 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_modelticket_manufacturerticket_ticketcategoryticket_and_more"),
        ("project_management", "0008_alter_projectaudithistory_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectStateTicket",
            fields=[
                (
                    "modelticket_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.modelticket",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        help_text="Ticket this Model belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="project_management.projectstate",
                        verbose_name="Ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project State Ticket",
                "verbose_name_plural": "Project State Tickets",
                "db_table": "project_management_projectstate_ticket",
                "managed": True,
            },
            bases=("core.modelticket",),
        ),
        migrations.CreateModel(
            name="ProjectTypeTicket",
            fields=[
                (
                    "modelticket_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.modelticket",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        help_text="Ticket this Model belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="project_management.projecttype",
                        verbose_name="Ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Type Ticket",
                "verbose_name_plural": "Project Type Tickets",
                "db_table": "project_management_projecttype_ticket",
                "managed": True,
            },
            bases=("core.modelticket",),
        ),
    ]
