# Generated by Django 5.1.10 on 2025-09-27 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_management", "0009_projectstateticket_projecttypeticket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectstateticket",
            name="model",
            field=models.ForeignKey(
                help_text="Model the ticket is for.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="project_management.projectstate",
                verbose_name="Model",
            ),
        ),
        migrations.AlterField(
            model_name="projecttypeticket",
            name="model",
            field=models.ForeignKey(
                help_text="Model the ticket is for.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="project_management.projecttype",
                verbose_name="Model",
            ),
        ),
    ]
