# Generated by Django 5.1.15 on 2026-02-09 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_remove_modelhistory_content_type_and_more"),
        ("project_management", "0010_alter_project_organization_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectTaskTicket",
            fields=[
                (
                    "ticketbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.ticketbase",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Task",
                "verbose_name_plural": "Project Tasks",
                "ordering": ["id"],
                "permissions": [
                    ("import_projecttaskticket", "Can import project task ticket"),
                    ("purge_projecttaskticket", "Can purge project task ticket"),
                    ("triage_projecttaskticket", "Can triage project task ticket"),
                ],
                "sub_model_type": "projecttask",
            },
            bases=("core.ticketbase",),
        ),
        migrations.DeleteModel(
            name="ProjectHistory",
        ),
        migrations.DeleteModel(
            name="ProjectMilestoneHistory",
        ),
        migrations.DeleteModel(
            name="ProjectMilestoneNotes",
        ),
        migrations.DeleteModel(
            name="ProjectNotes",
        ),
        migrations.DeleteModel(
            name="ProjectStateHistory",
        ),
        migrations.DeleteModel(
            name="ProjectStateNotes",
        ),
        migrations.DeleteModel(
            name="ProjectTypeHistory",
        ),
        migrations.DeleteModel(
            name="ProjectTypeNotes",
        ),
    ]
