# Generated by Django 5.1.15 on 2025-12-09 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project_management", "0011_projecttaskticket"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProjectHistory",
        ),
        migrations.DeleteModel(
            name="ProjectMilestoneHistory",
        ),
        migrations.DeleteModel(
            name="ProjectStateHistory",
        ),
        migrations.DeleteModel(
            name="ProjectTypeHistory",
        ),
    ]
