# Generated by Django 5.1.15 on 2025-12-09 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project_management", "0012_remove_projectmilestonehistory_model_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProjectMilestoneNotes",
        ),
        migrations.DeleteModel(
            name="ProjectNotes",
        ),
        migrations.DeleteModel(
            name="ProjectStateNotes",
        ),
        migrations.DeleteModel(
            name="ProjectTypeNotes",
        ),
    ]
