# docker exec -ti centurion-erp python manage.py migrate
# docker exec -ti centurion-erp python manage.py createsuperuser
version: "3.2"

services:

  centurion-erp:
    image: centurion-erp:dev
    build:
      context: ../.
      dockerfile: dockerfile
    container_name: centurion-erp
    hostname: centurion-erp
    ports:
      - "8002:8000"
    volumes:
      - ./volumes/data:/data:rw
      - ./volumes/etc/itsm:/etc/itsm:ro
    restart: always
    networks:
      - default
      - mariadb


  rabbitmq:
    image: rabbitmq:4.0.3-management-alpine
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_DEFAULT_VHOST=itsm
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - default

networks:
  mariadb:
    external: true
