# Generated by Django 5.1.5 on 2025-02-07 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_manufacturernotes'),
        ('itim', '0008_servicenotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterTypeNotes',
            fields=[
                ('modelnotes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.modelnotes')),
                ('model', models.ForeignKey(help_text='Model this note belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='itim.clustertype', verbose_name='Model')),
            ],
            options={
                'verbose_name': 'Cluster Type Note',
                'verbose_name_plural': 'Cluster Type Notes',
                'db_table': 'itim_cluster_type_notes',
                'ordering': ['-created'],
            },
            bases=('core.modelnotes',),
        ),
    ]
