# Generated by Django 5.1.8 on 2025-04-16 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itim', '0009_slmticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestTicket',
            fields=[
                ('slmticket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='itim.slmticket')),
            ],
            options={
                'verbose_name': 'Request',
                'verbose_name_plural': 'Requests',
                'ordering': ['id'],
                'permissions': [('import_requestticket', 'Can import request ticket'), ('purge_requestticket', 'Can purge request ticket'), ('triage_requestticket', 'Can triage request ticket')],
            },
            bases=('itim.slmticket',),
        ),
    ]
