# Generated by Django 5.1.9 on 2025-05-17 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_modelhistory_action_alter_modelhistory_after_and_more'),
        ('itim', '0010_alter_cluster_organization_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClusterHistory',
            new_name='ClusterAuditHistory',
        ),
        migrations.RenameModel(
            old_name='ClusterTypeHistory',
            new_name='ClusterTypeAuditHistory',
        ),
        migrations.RenameModel(
            old_name='PortHistory',
            new_name='PortAuditHistory',
        ),
        migrations.RenameModel(
            old_name='ServiceHistory',
            new_name='ServiceAuditHistory',
        ),
    ]
