# Generated by Django 5.1.9 on 2025-06-13 02:25

import access.models.tenancy_abstract
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0016_remove_tenant_slug_alter_tenant_manager_and_more"),
        ("core", "0033_alter_ticketcommentcategory_parent_and_more"),
        ("itam", "0023_remove_softwareversion_is_global_and_more"),
        ("itim", "0010_alter_cluster_organization_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cluster",
            name="is_global",
        ),
        migrations.RemoveField(
            model_name="cluster",
            name="slug",
        ),
        migrations.AlterField(
            model_name="cluster",
            name="cluster_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Type of Cluster",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="itim.clustertype",
                verbose_name="Cluster Type",
            ),
        ),
        migrations.AlterField(
            model_name="cluster",
            name="config",
            field=models.JSONField(
                blank=True,
                help_text="Cluster Configuration",
                null=True,
                verbose_name="Configuration",
            ),
        ),
        migrations.AlterField(
            model_name="cluster",
            name="devices",
            field=models.ManyToManyField(
                blank=True,
                help_text="Devices that are deployed upon the cluster.",
                related_name="cluster_device",
                to="itam.device",
                verbose_name="Devices",
            ),
        ),
        migrations.AlterField(
            model_name="cluster",
            name="id",
            field=models.AutoField(
                help_text="ID of the item",
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="cluster",
            name="model_notes",
            field=models.TextField(
                blank=True,
                help_text="Tid bits of information",
                null=True,
                verbose_name="Notes",
            ),
        ),
        migrations.AlterField(
            model_name="cluster",
            name="nodes",
            field=models.ManyToManyField(
                blank=True,
                help_text="Hosts for resource consumption that the cluster is deployed upon",
                related_name="cluster_node",
                to="itam.device",
                verbose_name="Nodes",
            ),
        ),
        migrations.AlterField(
            model_name="cluster",
            name="organization",
            field=models.ForeignKey(
                help_text="Tenant this belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="access.tenant",
                validators=[
                    access.models.tenancy_abstract.TenancyAbstractModel.validatate_organization_exists
                ],
                verbose_name="Tenant",
            ),
        ),
        migrations.AlterField(
            model_name="cluster",
            name="parent_cluster",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent Cluster for this cluster",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="itim.cluster",
                verbose_name="Parent Cluster",
            ),
        ),
        migrations.CreateModel(
            name="ClusterAuditHistory",
            fields=[
                (
                    "centurionaudit_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.centurionaudit",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        help_text="Model this history belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_history",
                        to="itim.cluster",
                        verbose_name="Model",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cluster History",
                "verbose_name_plural": "Cluster Histories",
                "db_table": "itim_cluster_audithistory",
                "managed": True,
            },
            bases=("core.centurionaudit",),
        ),
        migrations.CreateModel(
            name="ClusterCenturionModelNote",
            fields=[
                (
                    "centurionmodelnote_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.centurionmodelnote",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        help_text="Model this note belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="itim.cluster",
                        verbose_name="Model",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cluster Note",
                "verbose_name_plural": "Cluster Notes",
                "db_table": "itim_cluster_centurionmodelnote",
                "managed": True,
            },
            bases=("core.centurionmodelnote",),
        ),
    ]
