# Generated by Django 5.1.10 on 2025-09-27 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("itim", "0013_clusterticket_clustertypeticket_portticket_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clusterticket",
            name="model",
            field=models.ForeignKey(
                help_text="Model the ticket is for.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="itim.cluster",
                verbose_name="Model",
            ),
        ),
        migrations.AlterField(
            model_name="clustertypeticket",
            name="model",
            field=models.ForeignKey(
                help_text="Model the ticket is for.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="itim.clustertype",
                verbose_name="Model",
            ),
        ),
        migrations.AlterField(
            model_name="portticket",
            name="model",
            field=models.ForeignKey(
                help_text="Model the ticket is for.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="itim.port",
                verbose_name="Model",
            ),
        ),
        migrations.AlterField(
            model_name="serviceticket",
            name="model",
            field=models.ForeignKey(
                help_text="Model the ticket is for.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="itim.service",
                verbose_name="Model",
            ),
        ),
    ]
