# Generated by Django 5.1.9 on 2025-06-13 04:09

import access.models.tenancy_abstract
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0016_remove_tenant_slug_alter_tenant_manager_and_more"),
        ("core", "0033_alter_ticketcommentcategory_parent_and_more"),
        ("itam", "0023_remove_softwareversion_is_global_and_more"),
        ("itim", "0013_remove_port_is_global_alter_port_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="is_global",
        ),
        migrations.AlterField(
            model_name="service",
            name="cluster",
            field=models.ForeignKey(
                blank=True,
                help_text="Cluster the service is assigned to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="itim.cluster",
                verbose_name="Cluster",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="config",
            field=models.JSONField(
                blank=True,
                help_text="Cluster Configuration",
                null=True,
                verbose_name="Configuration",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="dependent_service",
            field=models.ManyToManyField(
                blank=True,
                help_text="Services that this service depends upon",
                related_name="dependentservice",
                to="itim.service",
                verbose_name="Dependent Services",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="device",
            field=models.ForeignKey(
                blank=True,
                help_text="Device the service is assigned to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="itam.device",
                verbose_name="Device",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="id",
            field=models.AutoField(
                help_text="ID of the item",
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="model_notes",
            field=models.TextField(
                blank=True,
                help_text="Tid bits of information",
                null=True,
                verbose_name="Notes",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="organization",
            field=models.ForeignKey(
                help_text="Tenant this belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="access.tenant",
                validators=[
                    access.models.tenancy_abstract.TenancyAbstractModel.validatate_organization_exists
                ],
                verbose_name="Tenant",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="template",
            field=models.ForeignKey(
                blank=True,
                help_text="Template this service uses",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="itim.service",
                verbose_name="Template Name",
            ),
        ),
        migrations.CreateModel(
            name="ServiceAuditHistory",
            fields=[
                (
                    "centurionaudit_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.centurionaudit",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        help_text="Model this history belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_history",
                        to="itim.service",
                        verbose_name="Model",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service History",
                "verbose_name_plural": "Service Histories",
                "db_table": "itim_service_audithistory",
                "managed": True,
            },
            bases=("core.centurionaudit",),
        ),
        migrations.CreateModel(
            name="ServiceCenturionModelNote",
            fields=[
                (
                    "centurionmodelnote_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.centurionmodelnote",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        help_text="Model this note belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="itim.service",
                        verbose_name="Model",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Note",
                "verbose_name_plural": "Service Notes",
                "db_table": "itim_service_centurionmodelnote",
                "managed": True,
            },
            bases=("core.centurionmodelnote",),
        ),
    ]
