# Generated by Django 5.1.15 on 2025-12-09 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("itim", "0015_changeticket_incidentticket_problemticket"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ClusterHistory",
        ),
        migrations.DeleteModel(
            name="ClusterTypeHistory",
        ),
        migrations.DeleteModel(
            name="PortHistory",
        ),
        migrations.DeleteModel(
            name="ServiceHistory",
        ),
    ]
