# Generated by Django 5.1.15 on 2026-02-12 06:43

import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_delete_modelhistory_delete_modelnotes_delete_notes_and_more"),
        ("itim", "0015_changeticket_incidentticket_problemticket_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ChangeTicket",
        ),
        migrations.DeleteModel(
            name="ProblemTicket",
        ),
    ]
