# Generated by Django 5.1.15 on 2025-12-09 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("itim", "0016_remove_clustertypehistory_model_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ClusterNotes",
        ),
        migrations.DeleteModel(
            name="ClusterTypeNotes",
        ),
        migrations.DeleteModel(
            name="PortNotes",
        ),
        migrations.DeleteModel(
            name="ServiceNotes",
        ),
    ]
