# Generated by Django 5.1.5 on 2025-02-07 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_manufacturernotes'),
        ('settings', '0008_alter_externallink_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalLinkNotes',
            fields=[
                ('modelnotes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.modelnotes')),
                ('model', models.ForeignKey(help_text='Model this note belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='settings.externallink', verbose_name='Model')),
            ],
            options={
                'verbose_name': 'External Link Note',
                'verbose_name_plural': 'External Link Notes',
                'db_table': 'settings_external_link_notes',
                'ordering': ['-created'],
            },
            bases=('core.modelnotes',),
        ),
    ]
