# Generated by Django 5.1.5 on 2025-02-20 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_data_move_history_to_new_table'),
        ('settings', '0011_externallinkhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettingsHistory',
            fields=[
                ('modelhistory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.modelhistory')),
                ('model', models.ForeignKey(help_text='Model this note belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='settings.appsettings', verbose_name='Model')),
            ],
            options={
                'verbose_name': 'App Settings History',
                'verbose_name_plural': 'App Settingsk History',
                'db_table': 'settings_appsettings_history',
                'ordering': ['-created'],
            },
            bases=('core.modelhistory',),
        ),
    ]
