# Generated by Django 5.1.9 on 2025-06-15 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0016_remove_tenant_slug_alter_tenant_manager_and_more"),
        ("core", "0033_alter_ticketcommentcategory_parent_and_more"),
        ("settings", "0012_alter_appsettings_global_organization_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appsettings",
            name="global_organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant global items will be created in",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="global_organization",
                to="access.tenant",
                verbose_name="Global Tenant",
            ),
        ),
        migrations.AlterField(
            model_name="appsettings",
            name="id",
            field=models.AutoField(
                help_text="ID of the item",
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="appsettings",
            name="owner_organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant the settings belong to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owner_organization",
                to="access.tenant",
            ),
        ),
        migrations.CreateModel(
            name="AppSettingsAuditHistory",
            fields=[
                (
                    "centurionaudit_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.centurionaudit",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        help_text="Model this history belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_history",
                        to="settings.appsettings",
                        verbose_name="Model",
                    ),
                ),
            ],
            options={
                "verbose_name": "App Settings History",
                "verbose_name_plural": "App Settings Histories",
                "db_table": "settings_appsettings_audithistory",
                "managed": True,
            },
            bases=("core.centurionaudit",),
        ),
    ]
