# Generated by Django 5.1.9 on 2025-05-17 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_rename_manufacturerhistory_manufactureraudithistory'),
        ('settings', '0012_alter_appsettings_global_organization_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppSettingsHistory',
            new_name='AppSettingsAuditHistory',
        ),
        migrations.RenameModel(
            old_name='ExternalLinkHistory',
            new_name='ExternalLinkAuditHistory',
        ),
    ]
