# Generated by Django 5.1.9 on 2025-06-16 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0016_remove_tenant_slug_alter_tenant_manager_and_more"),
        ("settings", "0014_remove_externallink_is_global_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersettings",
            name="default_organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Users default Tenant",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="access.tenant",
                verbose_name="Default Tenant",
            ),
        ),
        migrations.AlterField(
            model_name="usersettings",
            name="id",
            field=models.AutoField(
                help_text="ID of the item",
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="ID",
            ),
        ),
    ]
