# Generated by Django 5.1.10 on 2025-09-27 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0015_externallinkticket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externallinkticket",
            name="model",
            field=models.ForeignKey(
                help_text="Model the ticket is for.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="settings.externallink",
                verbose_name="Model",
            ),
        ),
    ]
