# Generated by Django 5.1.15 on 2025-12-09 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0016_alter_externallink_organization"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AppSettingsHistory",
        ),
        migrations.DeleteModel(
            name="ExternalLinkHistory",
        ),
    ]
