# Generated by Django 5.1.5 on 2025-02-07 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_management', '0006_configgroupnotes'),
        ('core', '0013_alter_manufacturer_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='config_group',
            field=models.ForeignKey(blank=True, default=None, help_text='Config group this note belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='config_management.configgroups', verbose_name='Config Group'),
        ),
    ]
