# Generated by Django 5.1.5 on 2025-02-07 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_notes_config_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturerNotes',
            fields=[
                ('modelnotes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.modelnotes')),
                ('model', models.ForeignKey(help_text='Model this note belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.manufacturer', verbose_name='Model')),
            ],
            options={
                'verbose_name': 'Manufacturer Note',
                'verbose_name_plural': 'Manufacturer Notes',
                'db_table': 'core_manufacturer_notes',
                'ordering': ['-created'],
            },
            bases=('core.modelnotes',),
        ),
    ]
