# Generated by Django 5.1.5 on 2025-02-16 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_manufacturerhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketCategoryHistory',
            fields=[
                ('modelhistory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.modelhistory')),
                ('model', models.ForeignKey(help_text='Model this note belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.ticketcategory', verbose_name='Model')),
            ],
            options={
                'verbose_name': 'Ticket Category History',
                'verbose_name_plural': 'Ticket Category History',
                'db_table': 'core_ticketcategory_history',
                'ordering': ['-created'],
            },
            bases=('core.modelhistory',),
        ),
    ]
