# Generated by Django 5.1.5 on 2025-03-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_data_move_history_to_new_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketlinkeditem',
            name='item_type',
            field=models.IntegerField(choices=[(1, 'Cluster'), (2, 'Config Group'), (3, 'Device'), (4, 'Operating System'), (5, 'Service'), (6, 'Software'), (7, 'Knowledge Base'), (8, 'Organization'), (9, 'Team'), (10, 'Feature Flag')], help_text='Python Model location for linked item', verbose_name='Item Type'),
        ),
    ]
