# Generated by Django 5.1.5 on 2025-03-03 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_ticketlinkeditem_item_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketCategoryNotes',
            fields=[
                ('modelnotes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.modelnotes')),
                ('model', models.ForeignKey(help_text='Model this note belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.ticketcategory', verbose_name='Model')),
            ],
            options={
                'verbose_name': 'Ticket Category Note',
                'verbose_name_plural': 'Ticket Category Notes',
                'db_table': 'core_ticketcategory_notes',
                'ordering': ['-created'],
            },
            bases=('core.modelnotes',),
        ),
        migrations.CreateModel(
            name='TicketCommentCategoryNotes',
            fields=[
                ('modelnotes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.modelnotes')),
                ('model', models.ForeignKey(help_text='Model this note belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.ticketcommentcategory', verbose_name='Model')),
            ],
            options={
                'verbose_name': 'Ticket Comment Category Note',
                'verbose_name_plural': 'Ticket Comment Category Notes',
                'db_table': 'core_ticketcommentcategory_notes',
                'ordering': ['-created'],
            },
            bases=('core.modelnotes',),
        ),
    ]
