# Generated by Django 5.1.8 on 2025-04-25 20:46

import core.models.ticket_base
import core.models.ticket_comment_base
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_ticketcommentbase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketcommentbase',
            name='body',
            field=models.TextField(blank=True, help_text='Comment contents', null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='ticketcommentbase',
            name='comment_type',
            field=models.CharField(choices=core.models.ticket_comment_base.TicketCommentBase.get_comment_type_choices, help_text='Type this comment is. derived from Meta.verbose_name', max_length=30, verbose_name='Type'),
        ),
    ]
