# Generated by Django 5.1.10 on 2025-08-23 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0024_centurionaudit_centurionmodelnote_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="assigned_teams",
            field=models.ManyToManyField(
                blank=True,
                help_text="Assign the ticket to a Group(s)",
                related_name="+",
                to="auth.group",
                verbose_name="Assigned Group(s)",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="subscribed_teams",
            field=models.ManyToManyField(
                blank=True,
                help_text="Subscribe a Group(s) to the ticket to receive updates",
                related_name="+",
                to="auth.group",
                verbose_name="Subscribed Group(s)",
            ),
        ),
        migrations.AlterField(
            model_name="ticketcomment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Parent ID for creating discussion threads",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.ticketcomment",
                verbose_name="Parent Comment",
            ),
        ),
        migrations.AlterField(
            model_name="ticketcomment",
            name="responsible_team",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Group whom is responsible for the completion of comment",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="auth.group",
                verbose_name="Responsible Group",
            ),
        ),
        migrations.AlterField(
            model_name="ticketcomment",
            name="responsible_user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="User whom is responsible for the completion of comment",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="comment_responsible_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsible User",
            ),
        ),
        migrations.AlterField(
            model_name="ticketcomment",
            name="user",
            field=models.ForeignKey(
                help_text="Who made the comment",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="comment_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
