# Generated by Django 5.1.9 on 2025-05-13 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_ticketbase_opened_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketCommentAction',
            fields=[
                ('ticketcommentbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.ticketcommentbase')),
            ],
            options={
                'verbose_name': 'Ticket Comment Action',
                'verbose_name_plural': 'Ticket Comment Actions',
                'ordering': ['id'],
                'permissions': [('import_ticketcommentaction', 'Can import ticket action comment.')],
                'sub_model_type': 'action',
            },
            bases=('core.ticketcommentbase',),
        ),
    ]
