# Generated by Django 5.1.8 on 2025-04-25 20:47

import core.models.ticket_base
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_ticketcommentbase'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketCommentSolution',
            fields=[
                ('ticketcommentbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.ticketcommentbase')),
            ],
            options={
                'verbose_name': 'Ticket Comment Solution',
                'verbose_name_plural': 'Ticket Comment Solutions',
                'ordering': ['id'],
                'sub_model_type': 'solution',
            },
            bases=('core.ticketcommentbase',),
        ),
    ]
