# Generated by Django 5.1.9 on 2025-05-17 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0010_company_alter_entity_entity_type_alter_person_dob_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0024_alter_modelhistory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelhistory',
            name='action',
            field=models.IntegerField(choices=[(1, 'Create'), (2, 'Update'), (3, 'Delete')], default=None, help_text='History action performed', null=True, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='modelhistory',
            name='after',
            field=models.JSONField(blank=True, default=None, help_text='Value Change to', null=True, verbose_name='After'),
        ),
        migrations.AlterField(
            model_name='modelhistory',
            name='before',
            field=models.JSONField(blank=True, default=None, help_text='Value before Change', null=True, verbose_name='Before'),
        ),
        migrations.AlterField(
            model_name='modelhistory',
            name='content_type',
            field=models.ForeignKey(blank=True, help_text='Model this history is for', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content Model'),
        ),
        migrations.AlterField(
            model_name='modelhistory',
            name='organization',
            field=models.ForeignKey(help_text='Tenancy this belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='access.tenant', verbose_name='Tenant'),
        ),
    ]
