# Generated by Django 5.1.10 on 2025-08-27 07:41

import core.models.centurion
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_alter_ticket_assigned_teams_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="centurionaudit",
            name="user",
            field=models.ForeignKey(
                help_text="User whom performed the action",
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                validators=[
                    core.models.centurion.CenturionModel.validate_field_not_none
                ],
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="modelhistory",
            name="user",
            field=models.ForeignKey(
                help_text="User whom performed the action this history relates to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="modelnotes",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User whom added the Note",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_notes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="modelnotes",
            name="modified_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="User whom modified the note",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="modified_notes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Edited By",
            ),
        ),
        migrations.AlterField(
            model_name="notes",
            name="usercreated",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="User whom added Note",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="usercreated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Added By",
            ),
        ),
        migrations.AlterField(
            model_name="notes",
            name="usermodified",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="User whom modified the note",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="usermodified",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Edited By",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="opened_by",
            field=models.ForeignKey(
                help_text="Who is the ticket for",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="opened_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Opened By",
            ),
        ),
    ]
