# Generated by Django 5.1.10 on 2025-09-18 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_alter_manufactureraudithistory_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticketbase",
            options={
                "ordering": ["id"],
                "permissions": [
                    ("import_ticketbase", "Can import a ticket base"),
                    ("purge_ticketbase", "Can purge a ticket base"),
                    ("triage_ticketbase", "Can triage a ticket base"),
                ],
                "verbose_name": "Ticket",
                "verbose_name_plural": "Tickets",
            },
        ),
    ]
