# Generated by Django 5.1.9 on 2025-05-17 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_modelhistory_action_alter_modelhistory_after_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ManufacturerHistory',
            new_name='ManufacturerAuditHistory',
        ),
    ]
