# Generated by Django 5.1.9 on 2025-05-24 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_centurionaudit_action_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centurionaudit',
            name='model_notes',
        ),
    ]
