# Generated by Django 5.1.8 on 2025-04-25 20:48

import core.models.ticket_base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_ticketcommentsolution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketbase',
            name='ticket_type',
            field=models.CharField(blank=True, choices=core.models.ticket_base.TicketBase.get_ticket_type_choices, default='ticket', help_text='Ticket Type. (derived from ticket model)', max_length=30, validators=[core.models.ticket_base.TicketBase.validate_not_null], verbose_name='Ticket Type'),
        ),
    ]
