# Generated by Django 5.1.8 on 2025-04-25 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_ticketbase_ticket_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketcommentbase',
            options={'ordering': ['id'], 'permissions': [('import_ticketcommentbase', 'Can import ticket comment.'), ('purge_ticketcommentbase', 'Can purge ticket comment.'), ('triage_ticketcommentbase', 'Can triage ticket comment.')], 'verbose_name': 'Ticket Comment', 'verbose_name_plural': 'Ticket Comments'},
        ),
    ]
