# Generated by Django 5.1.10 on 2025-09-22 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_alter_ticketbase_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticketcommentbase",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent ID for creating discussion threads",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="threads",
                to="core.ticketcommentbase",
                verbose_name="Parent Comment",
            ),
        ),
    ]
