# Generated by Django 5.1.10 on 2025-08-29 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_alter_centurionaudit_user_alter_modelhistory_user_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="manufactureraudithistory",
            options={
                "managed": True,
                "ordering": ["-created"],
                "verbose_name": "Manufacturer History",
                "verbose_name_plural": "Manufacturer Histories",
            },
        ),
        migrations.AlterModelOptions(
            name="ticketcategoryaudithistory",
            options={
                "managed": True,
                "ordering": ["-created"],
                "verbose_name": "Ticket Category History",
                "verbose_name_plural": "Ticket Category Histories",
            },
        ),
        migrations.AlterModelOptions(
            name="ticketcommentcategoryaudithistory",
            options={
                "managed": True,
                "ordering": ["-created"],
                "verbose_name": "Ticket Comment Category History",
                "verbose_name_plural": "Ticket Comment Category Histories",
            },
        ),
    ]
