# Generated by Django 5.1.8 on 2025-04-25 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_ticketcommentbase_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketcommentsolution',
            options={'ordering': ['id'], 'permissions': [('import_ticketcommentsolution', 'Can import ticket solution comment.'), ('purge_ticketcommentsolution', 'Can purge ticket solution comment.'), ('triage_ticketcommentsolution', 'Can triage ticket solution comment.')], 'verbose_name': 'Ticket Comment Solution', 'verbose_name_plural': 'Ticket Comment Solutions'},
        ),
    ]
