# Generated by Django 5.1.9 on 2025-06-05 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_centurionmodelnote"),
    ]

    operations = [
        migrations.DeleteModel(
            name="History",
        ),
    ]
