# Generated by Django 5.1.10 on 2025-09-25 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_modelticket_manufacturerticket_ticketcategoryticket_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="modelticket",
            options={
                "ordering": ["created"],
                "verbose_name": "Ticket Linked Model",
                "verbose_name_plural": "Ticket Linked Models",
            },
        ),
    ]
