# Generated by Django 5.1.8 on 2025-05-03 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_ticketcommentsolution_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketbase',
            name='parent_ticket',
            field=models.ForeignKey(blank=True, help_text='Parent of this ticket', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.ticketbase', verbose_name='Parent Ticket'),
        ),
    ]
