# Generated by Django 5.1.14 on 2025-11-08 06:53

import access.fields
import access.models.tenancy_abstract
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0017_alter_entity_organization_alter_role_organization"),
        ("core", "0029_remove_manufacturernotes_model_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketDependency",
            fields=[
                (
                    "id",
                    models.AutoField(
                        help_text="ID of the item",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    access.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Date and time of creation",
                        verbose_name="Created",
                    ),
                ),
                (
                    "how_related",
                    models.IntegerField(
                        choices=[(1, "Related"), (2, "Blocks"), (3, "Blocked By")],
                        help_text="How is the ticket related",
                        verbose_name="How Related",
                    ),
                ),
                (
                    "dependent_ticket",
                    models.ForeignKey(
                        help_text="The Related Ticket",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependent_ticket",
                        to="core.ticketbase",
                        verbose_name="Related Ticket",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Tenant this belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="access.tenant",
                        validators=[
                            access.models.tenancy_abstract.TenancyAbstractModel.validatate_organization_exists
                        ],
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        help_text="This Ticket",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket",
                        to="core.ticketbase",
                        verbose_name="Ticket",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Who added the dependency",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="access.entity",
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ticket Dependency",
                "verbose_name_plural": "Ticket Dependencies",
                "ordering": ["id"],
            },
        ),
    ]
