# Generated by Django 5.1.10 on 2025-09-27 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_alter_modelticket_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manufacturerticket",
            name="model",
            field=models.ForeignKey(
                help_text="Model the ticket is for.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="core.manufacturer",
                verbose_name="Model",
            ),
        ),
        migrations.AlterField(
            model_name="ticketcategoryticket",
            name="model",
            field=models.ForeignKey(
                help_text="Model the ticket is for.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="core.ticketcategory",
                verbose_name="Model",
            ),
        ),
        migrations.AlterField(
            model_name="ticketcommentcategoryticket",
            name="model",
            field=models.ForeignKey(
                help_text="Model the ticket is for.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="core.ticketcommentcategory",
                verbose_name="Model",
            ),
        ),
    ]
