# Generated by Django 5.1.15 on 2026-02-09 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0018_remove_contactticket_model_and_more"),
        ("assistance", "0011_remove_knowledgebasehistory_model_and_more"),
        ("core", "0030_remove_modelhistory_content_type_and_more"),
        ("devops", "0017_remove_featureflagnotes_model_and_more"),
        ("itam", "0020_remove_devicesoftwarehistory_devicehistory_ptr_and_more"),
        ("itim", "0015_changeticket_incidentticket_problemticket_and_more"),
        ("project_management", "0011_projecttaskticket_and_more"),
        ("settings", "0017_remove_externallinkhistory_model_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ModelHistory",
        ),
        migrations.DeleteModel(
            name="ModelNotes",
        ),
        migrations.DeleteModel(
            name="Notes",
        ),
        migrations.DeleteModel(
            name="TicketCategoryHistory",
        ),
        migrations.DeleteModel(
            name="TicketCategoryNotes",
        ),
        migrations.DeleteModel(
            name="TicketCommentCategoryHistory",
        ),
        migrations.DeleteModel(
            name="TicketCommentCategoryNotes",
        ),
    ]
