# Generated by Django 5.1.14 on 2025-11-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0017_alter_entity_organization_alter_role_organization"),
        ("core", "0030_ticketdependency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticketbase",
            name="assigned_to",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users / Groups assigned to the ticket",
                related_name="ticket_assigned",
                to="access.entity",
                verbose_name="Assignees",
            ),
        ),
        migrations.AlterField(
            model_name="ticketbase",
            name="subscribed_to",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users / Groups subscribed to the ticket",
                related_name="ticket_subscription",
                to="access.entity",
                verbose_name="Subscribers",
            ),
        ),
    ]
