# Generated by Django 5.1.9 on 2025-06-09 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistance", "0013_alter_modelknowledgebasearticle_model"),
        ("core", "0031_remove_ticketcategory_is_global_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticketcategory",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="The Parent Category",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.ticketcategory",
                verbose_name="Parent Category",
            ),
        ),
        migrations.AlterField(
            model_name="ticketcategory",
            name="runbook",
            field=models.ForeignKey(
                blank=True,
                help_text="The runbook for this category",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="assistance.knowledgebase",
                verbose_name="Runbook",
            ),
        ),
    ]
