# Generated by Django 5.1.15 on 2026-02-25 07:24

import core.models.ticket_base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_delete_modelhistory_delete_modelnotes_delete_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketbase',
            name='ticket_type',
            field=models.CharField(blank=True, help_text='Ticket Type. (derived from ticket model)', max_length=30, validators=[core.models.ticket_base.TicketBase.validate_not_null], verbose_name='Ticket Type'),
        ),
    ]
