# Generated by Django 5.1.14 on 2025-11-25 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0018_remove_contactticket_model_and_more"),
        ("core", "0031_alter_ticketbase_assigned_to_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketCommentTask",
            fields=[
                (
                    "ticketcommentbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.ticketcommentbase",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "To Do"), (2, "Done")],
                        default=1,
                        help_text="Status of task",
                        verbose_name="Status",
                    ),
                ),
                (
                    "planned_start_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Planned start date.",
                        null=True,
                        verbose_name="Planned Start Date",
                    ),
                ),
                (
                    "planned_finish_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Planned finish date",
                        null=True,
                        verbose_name="Planned Finish Date",
                    ),
                ),
                (
                    "real_start_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Real start date",
                        null=True,
                        verbose_name="Real Start Date",
                    ),
                ),
                (
                    "real_finish_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Real finish date",
                        null=True,
                        verbose_name="Real Finish Date",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="Is the comment deleted? And ready to be purged",
                        verbose_name="Deleted",
                    ),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="whom is responsible for the completion of comment",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="access.entity",
                        verbose_name="Assignee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ticket Comment Task",
                "verbose_name_plural": "Ticket Comment Task",
                "ordering": ["id"],
                "permissions": [
                    ("import_ticketcommenttask", "Can import ticket task comment."),
                    ("purge_ticketcommenttask", "Can purge ticket task comment."),
                    ("triage_ticketcommenttask", "Can triage ticket task comment."),
                ],
                "sub_model_type": "task",
            },
            bases=("core.ticketcommentbase",),
        ),
    ]
