# Generated by Django 5.1.15 on 2026-05-30 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_delete_modelhistory_delete_modelnotes_delete_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketbase',
            name='ticket_type',
        ),
        migrations.RemoveField(
            model_name='ticketcommentbase',
            name='comment_type',
        ),
    ]
