# Generated by Django 5.1.14 on 2025-11-30 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_ticketcommenttask"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticketcommentbase",
            options={
                "ordering": ["id"],
                "permissions": [
                    ("import_ticketcommentbase", "Can import ticket comment."),
                    ("purge_ticketcommentbase", "Can purge ticket comment."),
                ],
                "verbose_name": "Ticket Comment",
                "verbose_name_plural": "Ticket Comments",
            },
        ),
        migrations.AlterModelOptions(
            name="ticketcommentsolution",
            options={
                "ordering": ["id"],
                "permissions": [
                    (
                        "import_ticketcommentsolution",
                        "Can import ticket solution comment.",
                    ),
                    (
                        "purge_ticketcommentsolution",
                        "Can purge ticket solution comment.",
                    ),
                ],
                "verbose_name": "Ticket Comment Solution",
                "verbose_name_plural": "Ticket Comment Solutions",
            },
        ),
        migrations.AlterModelOptions(
            name="ticketcommenttask",
            options={
                "ordering": ["id"],
                "permissions": [
                    ("import_ticketcommenttask", "Can import ticket task comment."),
                    ("purge_ticketcommenttask", "Can purge ticket task comment."),
                ],
                "verbose_name": "Ticket Comment Task",
                "verbose_name_plural": "Ticket Comment Task",
            },
        ),
    ]
