# Generated by Django 5.1.15 on 2026-02-25 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_ticketbase_ticket_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketbase',
            name='ticket_type',
        ),
    ]
