# Generated by Django 5.1.15 on 2026-06-15 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0032_remove_ticketbase_ticket_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketCommentActionFieldEdit',
            fields=[
                ('ticketcommentaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.ticketcommentaction')),
                ('field_name', models.CharField(help_text='Name of the field that was changed', max_length=50, verbose_name='Field Name')),
                ('previous_value', models.CharField(blank=True, help_text='Value changed from', max_length=50, null=True, verbose_name='Previous Value')),
                ('new_value', models.CharField(blank=True, help_text='Value changed to', max_length=50, null=True, verbose_name='New Value')),
            ],
            options={
                'verbose_name': 'Ticket Field Change Action Comment',
                'verbose_name_plural': 'Ticket Field Change Action Comments',
                'ordering': ['id'],
                'permissions': [('import_ticketcommentactionfieldedit', 'Can import ticket field change action comment.')],
            },
            bases=('core.ticketcommentaction',),
        ),
        migrations.CreateModel(
            name='TicketCommentActionTicketDependency',
            fields=[
                ('ticketcommentaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.ticketcommentaction')),
                ('is_create', models.BooleanField(default=True, help_text='is this an add operation?', verbose_name='Adding link')),
                ('link_type', models.IntegerField(choices=[(1, 'Related'), (2, 'Blocks'), (3, 'Blocked By')], help_text='How is the ticket related', verbose_name='How Related')),
                ('dependent_ticket_id', models.IntegerField(default=0, help_text='ID of ticket', verbose_name='Ticket ID')),
            ],
            options={
                'verbose_name': 'Ticket Dependency Action Comment',
                'verbose_name_plural': 'Ticket Dependency Action Comments',
                'ordering': ['id'],
                'permissions': [('import_ticketcommentactionticketdependency', 'Can import ticket dependency action comment.')],
            },
            bases=('core.ticketcommentaction',),
        ),
        migrations.CreateModel(
            name='TicketCommentActionModelLink',
            fields=[
                ('ticketcommentaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.ticketcommentaction')),
                ('is_create', models.BooleanField(default=True, help_text='is this an add operation?', verbose_name='Adding link')),
                ('model_id', models.IntegerField(default=0, help_text='ID of model', verbose_name='Model ID')),
                ('content_type', models.ForeignKey(help_text='Content ID of the model', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype', verbose_name='Content ID for model')),
            ],
            options={
                'verbose_name': 'Ticket Linked Model Action Comment',
                'verbose_name_plural': 'Ticket Linked Model Action Comments',
                'ordering': ['id'],
                'permissions': [('import_ticketcommentactionmodellink', 'Can import ticket model link action comment.')],
            },
            bases=('core.ticketcommentaction',),
        ),
    ]
