# Generated by Django 5.1.15 on 2026-06-21 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_ticketcommentactionfieldedit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketdependency',
            name='dependent_ticket',
            field=models.ForeignKey(help_text='The Related Ticket', on_delete=django.db.models.deletion.PROTECT, related_name='dependent_ticket', to='core.ticketbase', verbose_name='Related Ticket'),
        ),
        migrations.AlterField(
            model_name='ticketdependency',
            name='ticket',
            field=models.ForeignKey(help_text='This Ticket', on_delete=django.db.models.deletion.PROTECT, related_name='ticket', to='core.ticketbase', verbose_name='Ticket'),
        ),
        migrations.AlterUniqueTogether(
            name='ticketdependency',
            unique_together={('ticket', 'dependent_ticket')},
        ),
    ]
