# Generated by Django 5.1.15 on 2026-02-25 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_remove_ticketbase_ticket_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketcommentbase',
            name='comment_type',
        ),
    ]
