# Generated by Django 5.1.15 on 2025-12-09 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0019_remove_organizationnotes_model_and_more"),
        ("assistance", "0011_remove_knowledgebasehistory_model_and_more"),
        ("config_management", "0013_remove_configgroupshistory_model_and_more"),
        ("core", "0033_alter_ticketcommentbase_options_and_more"),
        ("devops", "0018_remove_gitgrouphistory_model_and_more"),
        ("itam", "0021_remove_deviceoperatingsystemhistory_devicehistory_ptr_and_more"),
        ("itim", "0016_remove_clustertypehistory_model_and_more"),
        ("project_management", "0012_remove_projectmilestonehistory_model_and_more"),
        ("settings", "0017_remove_externallinkhistory_model_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ModelHistory",
        ),
        migrations.DeleteModel(
            name="TicketCategoryHistory",
        ),
        migrations.DeleteModel(
            name="TicketCommentCategoryHistory",
        ),
    ]
