# Generated by Django 5.1.15 on 2025-12-09 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assistance", "0012_remove_knowledgecategorybasenotes_model_and_more"),
        ("config_management", "0014_delete_configgroupnotes"),
        ("core", "0034_remove_ticketcommentcategoryhistory_modelhistory_ptr_and_more"),
        ("devops", "0019_remove_gitgroupnotes_model_and_more"),
        ("itam", "0022_remove_devicenotes_model_and_more"),
        ("itim", "0017_remove_clustertypenotes_model_and_more"),
        ("project_management", "0013_remove_projectnotes_model_and_more"),
        ("settings", "0018_delete_externallinknotes"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ModelNotes",
        ),
        migrations.DeleteModel(
            name="Notes",
        ),
        migrations.DeleteModel(
            name="TicketCategoryNotes",
        ),
        migrations.DeleteModel(
            name="TicketCommentCategoryNotes",
        ),
    ]
