# Generated by Django 5.1.15 on 2026-06-23 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_ticketdependency_dependent_ticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcommentactionfieldedit',
            name='edit_type',
            field=models.IntegerField(choices=[(0, 'Add'), (1, 'Edit'), (2, 'Remove')], default=1, help_text='Enables distinguishing between m2m (Add, Remove) and other fields (Edit)', verbose_name='Edit Type'),
        ),
    ]
