# Generated by Django 5.1.15 on 2026-02-05 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_remove_ticketcommentcategorynotes_modelnotes_ptr_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticketcommentbase",
            name="ticket",
            field=models.ForeignKey(
                help_text="Ticket this comment belongs to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.ticketbase",
                verbose_name="Ticket",
            ),
        ),
    ]
