# Generated by Django 5.1.10 on 2025-07-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_alter_ticketcommentbase_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticketbase",
            name="external_ref",
            field=models.IntegerField(
                blank=True,
                help_text="External System reference",
                null=True,
                verbose_name="Reference Number",
            ),
        ),
        migrations.AlterField(
            model_name="ticketbase",
            name="external_system",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Github"),
                    (2, "Gitlab"),
                    (9999, "Custom #1 (Imported)"),
                    (9998, "Custom #2 (Imported)"),
                    (9997, "Custom #3 (Imported)"),
                    (9996, "Custom #4 (Imported)"),
                    (9995, "Custom #5 (Imported)"),
                    (9994, "Custom #6 (Imported)"),
                    (9993, "Custom #7 (Imported)"),
                    (9992, "Custom #8 (Imported)"),
                    (9991, "Custom #9 (Imported)"),
                ],
                help_text="External system this item derives",
                null=True,
                verbose_name="External System",
            ),
        ),
    ]
