# Generated by Django 5.1.10 on 2025-07-23 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0036_alter_ticketbase_external_ref_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="centurionmodelnote",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Model this note is for",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
                verbose_name="Content Model",
            ),
        ),
        migrations.AlterField(
            model_name="centurionmodelnote",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User whom added the Note",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
    ]
