# Generated by Django 5.1.10 on 2025-09-23 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_modelticket_manufacturerticket_ticketcategoryticket_and_more"),
        ("human_resources", "0003_alter_employeeaudithistory_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeTicket",
            fields=[
                (
                    "modelticket_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.modelticket",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        help_text="Ticket this Model belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="human_resources.employee",
                        verbose_name="Ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee Ticket",
                "verbose_name_plural": "Employee Tickets",
                "db_table": "human_resources_employee_ticket",
                "managed": True,
            },
            bases=("core.modelticket",),
        ),
    ]
