# Generated by Django 5.1.14 on 2025-11-19 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("human_resources", "0006_alter_employee_employee_number"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmployeeTicket",
        ),
    ]
