# Generated by Django 5.1.5 on 2025-02-07 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0004_alter_knowledgebase_organization_and_more'),
        ('core', '0013_alter_manufacturer_organization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBaseNotes',
            fields=[
                ('modelnotes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.modelnotes')),
                ('model', models.ForeignKey(help_text='Model this note belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='assistance.knowledgebase', verbose_name='Model')),
            ],
            options={
                'verbose_name': 'Knowledge Base Article Note',
                'verbose_name_plural': 'Knowledge Base Article Notes',
                'db_table': 'assistance_knowledge_base_notes',
                'ordering': ['-created'],
            },
            bases=('core.modelnotes',),
        ),
    ]
