# Generated by Django 5.1.5 on 2025-02-08 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0005_knowledgebasenotes'),
        ('core', '0015_manufacturernotes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knowledgebasenotes',
            options={'ordering': ['-created'], 'verbose_name': 'Knowledge Base Note', 'verbose_name_plural': 'Knowledge Base Notes'},
        ),
        migrations.CreateModel(
            name='KnowledgeCategoryBaseNotes',
            fields=[
                ('modelnotes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.modelnotes')),
                ('model', models.ForeignKey(help_text='Model this note belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='assistance.knowledgebasecategory', verbose_name='Model')),
            ],
            options={
                'verbose_name': 'Knowledge Base CategoryNote',
                'verbose_name_plural': 'Knowledge Base CategoryNotes',
                'db_table': 'assistance_knowledge_base_category_notes',
                'ordering': ['-created'],
            },
            bases=('core.modelnotes',),
        ),
    ]
