# Generated by Django 5.1.9 on 2025-05-17 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0006_alter_knowledgebase_organization_and_more'),
        ('core', '0025_alter_modelhistory_action_alter_modelhistory_after_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KnowledgeBaseHistory',
            new_name='KnowledgeBaseAuditHistory',
        ),
        migrations.RenameModel(
            old_name='KnowledgeBaseCategoryHistory',
            new_name='KnowledgeBaseCategoryAuditHistory',
        ),
    ]
