# Generated by Django 5.1.9 on 2025-06-03 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistance", "0008_knowledgebaseaudithistory_and_more"),
        ("core", "0027_centurionmodelnote"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeBaseCategoryAuditHistory",
            fields=[
                (
                    "centurionaudit_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.centurionaudit",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        help_text="Model this history belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_history",
                        to="assistance.knowledgebasecategory",
                        verbose_name="Model",
                    ),
                ),
            ],
            options={
                "verbose_name": "Knowledge Base Category History",
                "verbose_name_plural": "Knowledge Base Category Histories",
                "db_table": "assistance_knowledgebasecategory_audithistory",
                "managed": True,
            },
            bases=("core.centurionaudit", models.Model),
        ),
        migrations.CreateModel(
            name="KnowledgeBaseCategoryCenturionModelNote",
            fields=[
                (
                    "centurionmodelnote_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.centurionmodelnote",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        help_text="Model this note belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="assistance.knowledgebasecategory",
                        verbose_name="Model",
                    ),
                ),
            ],
            options={
                "verbose_name": "Knowledge Base Category Note",
                "verbose_name_plural": "Knowledge Base Category Notes",
                "db_table": "assistance_knowledgebasecategory_centurionmodelnote",
                "managed": True,
            },
            bases=("core.centurionmodelnote", models.Model),
        ),
    ]
