# Generated by Django 5.1.10 on 2025-09-23 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistance", "0008_alter_knowledgebaseaudithistory_options_and_more"),
        ("core", "0028_modelticket_manufacturerticket_ticketcategoryticket_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeBaseCategoryTicket",
            fields=[
                (
                    "modelticket_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.modelticket",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        help_text="Ticket this Model belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="assistance.knowledgebasecategory",
                        verbose_name="Ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Knowledge Base Category Ticket",
                "verbose_name_plural": "Knowledge Base Category Tickets",
                "db_table": "assistance_knowledgebasecategory_ticket",
                "managed": True,
            },
            bases=("core.modelticket",),
        ),
        migrations.CreateModel(
            name="KnowledgeBaseTicket",
            fields=[
                (
                    "modelticket_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.modelticket",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        help_text="Ticket this Model belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="assistance.knowledgebase",
                        verbose_name="Ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Knowledge Base Ticket",
                "verbose_name_plural": "Knowledge Base Tickets",
                "db_table": "assistance_knowledgebase_ticket",
                "managed": True,
            },
            bases=("core.modelticket",),
        ),
    ]
