# Generated by Django 5.1.10 on 2025-08-27 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistance", "0008_alter_knowledgebase_responsible_teams_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="knowledgebasecategory",
            name="target_user",
            field=models.ForeignKey(
                blank=True,
                help_text="User(s) to grant access to the article",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Target Users(s)",
            ),
        ),
    ]
