# Generated by Django 5.1.10 on 2025-08-29 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assistance", "0009_alter_knowledgebasecategory_target_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="knowledgebaseaudithistory",
            options={
                "managed": True,
                "ordering": ["-created"],
                "verbose_name": "Knowledge Base History",
                "verbose_name_plural": "Knowledge Base Histories",
            },
        ),
        migrations.AlterModelOptions(
            name="knowledgebasecategoryaudithistory",
            options={
                "managed": True,
                "ordering": ["-created"],
                "verbose_name": "Knowledge Base Category History",
                "verbose_name_plural": "Knowledge Base Category Histories",
            },
        ),
    ]
