# Generated by Django 5.1.9 on 2025-06-03 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0010_company_alter_entity_entity_type_alter_person_dob_and_more"),
        ("assistance", "0009_knowledgebasecategoryaudithistory_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="knowledgebase",
            name="category",
            field=models.ForeignKey(
                help_text="Article Category",
                max_length=50,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="assistance.knowledgebasecategory",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="knowledgebase",
            name="content",
            field=models.TextField(
                blank=True,
                help_text="Content of the article. Markdown is supported",
                null=True,
                verbose_name="Article Content",
            ),
        ),
        migrations.AlterField(
            model_name="knowledgebase",
            name="expiry_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Date the article will be removed from published articles",
                null=True,
                verbose_name="End Date",
            ),
        ),
        migrations.AlterField(
            model_name="knowledgebase",
            name="release_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Date the article will be published",
                null=True,
                verbose_name="Publish Date",
            ),
        ),
        migrations.AlterField(
            model_name="knowledgebase",
            name="responsible_teams",
            field=models.ManyToManyField(
                blank=True,
                help_text="Team(s) whom is considered the articles owner.",
                related_name="responsible_teams",
                to="access.team",
                verbose_name="Responsible Team(s)",
            ),
        ),
        migrations.AlterField(
            model_name="knowledgebase",
            name="responsible_user",
            field=models.ForeignKey(
                help_text="User(s) whom is considered the articles owner.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="responsible_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsible User",
            ),
        ),
        migrations.AlterField(
            model_name="knowledgebase",
            name="summary",
            field=models.TextField(
                blank=True,
                help_text="Short Summary of the article",
                null=True,
                verbose_name="Summary",
            ),
        ),
        migrations.AlterField(
            model_name="knowledgebase",
            name="target_team",
            field=models.ManyToManyField(
                blank=True,
                help_text="Team(s) to grant access to the article",
                to="access.team",
                verbose_name="Target Team(s)",
            ),
        ),
        migrations.AlterField(
            model_name="knowledgebase",
            name="target_user",
            field=models.ForeignKey(
                blank=True,
                help_text="User(s) to grant access to the article",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Target Users(s)",
            ),
        ),
    ]
