# Generated by Django 5.1.10 on 2025-09-27 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistance", "0009_knowledgebasecategoryticket_knowledgebaseticket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="knowledgebasecategoryticket",
            name="model",
            field=models.ForeignKey(
                help_text="Model the ticket is for.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="assistance.knowledgebasecategory",
                verbose_name="Model",
            ),
        ),
        migrations.AlterField(
            model_name="knowledgebaseticket",
            name="model",
            field=models.ForeignKey(
                help_text="Model the ticket is for.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="assistance.knowledgebase",
                verbose_name="Model",
            ),
        ),
    ]
