# Generated by Django 5.1.9 on 2025-06-03 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistance", "0010_alter_knowledgebase_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgebase",
            name="model_notes",
            field=models.TextField(
                blank=True,
                help_text="Tid bits of information",
                null=True,
                verbose_name="Notes",
            ),
        ),
    ]
