# Generated by Django 5.1.15 on 2026-02-09 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assistance", "0010_alter_knowledgebase_organization_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="KnowledgeBaseCategoryHistory",
        ),
        migrations.DeleteModel(
            name="KnowledgeBaseHistory",
        ),
        migrations.DeleteModel(
            name="KnowledgeBaseNotes",
        ),
        migrations.DeleteModel(
            name="KnowledgeCategoryBaseNotes",
        ),
    ]
