# Generated by Django 5.1.9 on 2025-06-04 00:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0010_company_alter_entity_entity_type_alter_person_dob_and_more"),
        ("assistance", "0011_knowledgebase_model_notes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="knowledgebasecategory",
            name="parent_category",
            field=models.ForeignKey(
                blank=True,
                help_text="Category this category belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="assistance.knowledgebasecategory",
                verbose_name="Parent Category",
            ),
        ),
        migrations.AlterField(
            model_name="knowledgebasecategory",
            name="target_team",
            field=models.ManyToManyField(
                blank=True,
                help_text="Team(s) to grant access to the article",
                to="access.team",
                verbose_name="Target Team(s)",
            ),
        ),
        migrations.AlterField(
            model_name="knowledgebasecategory",
            name="target_user",
            field=models.ForeignKey(
                blank=True,
                help_text="User(s) to grant access to the article",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Target Users(s)",
            ),
        ),
    ]
