# Generated by Django 5.1.15 on 2025-12-09 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assistance", "0011_remove_knowledgebasehistory_model_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="KnowledgeBaseNotes",
        ),
        migrations.DeleteModel(
            name="KnowledgeCategoryBaseNotes",
        ),
    ]
