# Generated by Django 5.1.9 on 2025-06-06 02:40

import assistance.models.model_knowledge_base_article
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistance", "0012_alter_knowledgebasecategory_parent_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelknowledgebasearticle",
            name="model",
            field=models.CharField(
                choices=assistance.models.model_knowledge_base_article.all_models,
                help_text="Model type to link to article article",
                max_length=80,
                verbose_name="Model Type",
            ),
        ),
    ]
