# Generated by Django 5.1.10 on 2025-07-29 04:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistance", "0013_alter_modelknowledgebasearticle_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="knowledgebase",
            name="responsible_user",
            field=models.ForeignKey(
                blank=True,
                help_text="User(s) whom is considered the articles owner.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="responsible_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsible User",
            ),
        ),
    ]
