# Generated by Django 5.1.5 on 2025-03-03 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_ticketlinkeditem_item_type'),
        ('devops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlagNotes',
            fields=[
                ('modelnotes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.modelnotes')),
                ('model', models.ForeignKey(help_text='Model this note belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='devops.featureflag', verbose_name='Model')),
            ],
            options={
                'verbose_name': 'Feature Flag Note',
                'verbose_name_plural': 'Feature Flag Notes',
                'db_table': 'devops_feature_flag_notes',
                'ordering': ['-created'],
            },
            bases=('core.modelnotes',),
        ),
    ]
