# Generated by Django 5.1.5 on 2025-03-04 15:56

import access.fields
import access.models.tenancy
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0004_organizationhistory_teamhistory'),
        ('devops', '0002_featureflagnotes'),
        ('itam', '0010_alter_software_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureflag',
            name='software',
            field=models.ForeignKey(help_text='Software this feature flag is for', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature_flags', to='itam.software', verbose_name='Software'),
        ),
        migrations.CreateModel(
            name='SoftwareEnableFeatureFlag',
            fields=[
                ('id', models.AutoField(help_text='Primary key of the entry', primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Is feature flagging enabled for this software', verbose_name='Enabled')),
                ('created', access.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, help_text='Date and time of creation', verbose_name='Created')),
                ('modified', access.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, help_text='Date and time of last modification', verbose_name='Modified')),
                ('organization', models.ForeignKey(help_text='Organization this belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='access.organization', validators=[access.models.tenancy.TenancyObject.validatate_organization_exists], verbose_name='Organization')),
                ('software', models.ForeignKey(help_text='Software this feature flag is for', on_delete=django.db.models.deletion.CASCADE, related_name='feature_flagging', to='itam.software', verbose_name='Software')),
            ],
            options={
                'verbose_name': 'Software Feature Flagging',
                'verbose_name_plural': 'Software Feature Flaggings',
                'ordering': ['software', 'organization'],
                'unique_together': {('organization', 'software')},
            },
        ),
    ]
