# Generated by Django 5.1.5 on 2025-03-07 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0005_alter_featureflag_software'),
        ('itam', '0010_alter_software_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureflag',
            name='software',
            field=models.ForeignKey(help_text='Software this feature flag is for', limit_choices_to={'feature_flagging__enabled': True}, on_delete=django.db.models.deletion.PROTECT, related_name='feature_flags', to='itam.software', verbose_name='Software'),
        ),
        migrations.AlterField(
            model_name='softwareenablefeatureflag',
            name='software',
            field=models.ForeignKey(help_text='Software this feature flag is for', on_delete=django.db.models.deletion.PROTECT, related_name='feature_flagging', to='itam.software', verbose_name='Software'),
        ),
    ]
