# Generated by Django 5.1.5 on 2025-03-08 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0006_alter_featureflag_software_and_more'),
        ('itam', '0010_alter_software_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureflag',
            name='software',
            field=models.ForeignKey(help_text='Software this feature flag is for', on_delete=django.db.models.deletion.PROTECT, related_name='feature_flags', to='itam.software', verbose_name='Software'),
        ),
    ]
