# Generated by Django 5.1.5 on 2025-03-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0008_checkin'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='version',
            field=models.TextField(blank=True, help_text='Version of the deployed software', max_length=80, null=True, verbose_name='Deployed Version'),
        ),
    ]
