# Generated by Django 5.1.9 on 2025-05-24 23:48

import access.models.tenancy_abstract
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0010_company_alter_entity_entity_type_alter_person_dob_and_more'),
        ('core', '0026_remove_centurionaudit_model_notes'),
        ('devops', '0012_alter_checkin_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gitgroup',
            name='id',
            field=models.AutoField(help_text='ID of the item', primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gitgroup',
            name='model_notes',
            field=models.TextField(blank=True, help_text='Tid bits of information', null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='gitgroup',
            name='organization',
            field=models.ForeignKey(help_text='Tenant this belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='access.tenant', validators=[access.models.tenancy_abstract.TenancyAbstractModel.validatate_organization_exists], verbose_name='Tenant'),
        ),
        migrations.CreateModel(
            name='GitGroupAuditHistory',
            fields=[
                ('centurionaudit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.centurionaudit')),
                ('model', models.ForeignKey(help_text='Model this history belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='audit_history', to='devops.gitgroup', verbose_name='Model')),
            ],
            options={
                'verbose_name': 'GIT Group History',
                'verbose_name_plural': 'GIT Group Histories',
                'db_table': 'devops_gitgroup_audithistory',
                'managed': True,
            },
            bases=('core.centurionaudit', models.Model),
        ),
    ]
