# Generated by Django 5.1.9 on 2025-05-17 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_rename_manufacturerhistory_manufactureraudithistory'),
        ('devops', '0012_alter_checkin_organization_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeatureFlagHistory',
            new_name='FeatureFlagAuditHistory',
        ),
        migrations.RenameModel(
            old_name='GitGroupHistory',
            new_name='GitGroupAuditHistory',
        ),
        migrations.RenameModel(
            old_name='GitHubHistory',
            new_name='GitHubAuditHistory',
        ),
        migrations.RenameModel(
            old_name='GitlabHistory',
            new_name='GitlabAuditHistory',
        ),
    ]
