# Generated by Django 5.1.9 on 2025-05-29 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devops", "0013_alter_gitgroup_id_alter_gitgroup_model_notes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gitgroup",
            name="parent_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent Git Group this repository belongs to.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="devops.gitgroup",
                verbose_name="Parent Group",
            ),
        ),
    ]
