# Generated by Django 5.1.9 on 2025-05-29 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_centurionmodelnote"),
        ("devops", "0014_alter_gitgroup_parent_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="GitGroupCenturionModelNote",
            fields=[
                (
                    "centurionmodelnote_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.centurionmodelnote",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        help_text="Model this note belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="devops.gitgroup",
                        verbose_name="Model",
                    ),
                ),
            ],
            options={
                "verbose_name": "GIT Group Note",
                "verbose_name_plural": "GIT Group Notes",
                "db_table": "devops_gitgroup_centurionmodelnote",
                "managed": True,
            },
            bases=("core.centurionmodelnote", models.Model),
        ),
    ]
