# Generated by Django 5.1.10 on 2025-09-27 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devops", "0015_featureflagticket_gitgroupticket_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featureflagticket",
            name="model",
            field=models.ForeignKey(
                help_text="Model the ticket is for.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="devops.featureflag",
                verbose_name="Model",
            ),
        ),
        migrations.AlterField(
            model_name="gitgroupticket",
            name="model",
            field=models.ForeignKey(
                help_text="Model the ticket is for.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="devops.gitgroup",
                verbose_name="Model",
            ),
        ),
        migrations.AlterField(
            model_name="githubrepositoryticket",
            name="model",
            field=models.ForeignKey(
                help_text="Model the ticket is for.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="devops.githubrepository",
                verbose_name="Model",
            ),
        ),
        migrations.AlterField(
            model_name="gitlabrepositoryticket",
            name="model",
            field=models.ForeignKey(
                help_text="Model the ticket is for.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="devops.gitlabrepository",
                verbose_name="Model",
            ),
        ),
        migrations.AlterField(
            model_name="gitrepositoryticket",
            name="model",
            field=models.ForeignKey(
                help_text="Model the ticket is for.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="devops.gitrepository",
                verbose_name="Model",
            ),
        ),
    ]
