# Generated by Django 5.1.9 on 2025-05-30 19:28

import access.models.tenancy_abstract
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0010_company_alter_entity_entity_type_alter_person_dob_and_more"),
        ("core", "0027_centurionmodelnote"),
        ("devops", "0015_gitgroupcenturionmodelnote"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featureflag",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Description of this feature",
                max_length=300,
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="featureflag",
            name="id",
            field=models.AutoField(
                help_text="ID of the item",
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="featureflag",
            name="model_notes",
            field=models.TextField(
                blank=True,
                help_text="Tid bits of information",
                null=True,
                verbose_name="Notes",
            ),
        ),
        migrations.AlterField(
            model_name="featureflag",
            name="organization",
            field=models.ForeignKey(
                help_text="Tenant this belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="access.tenant",
                validators=[
                    access.models.tenancy_abstract.TenancyAbstractModel.validatate_organization_exists
                ],
                verbose_name="Tenant",
            ),
        ),
        migrations.CreateModel(
            name="FeatureFlagAuditHistory",
            fields=[
                (
                    "centurionaudit_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.centurionaudit",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        help_text="Model this history belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_history",
                        to="devops.featureflag",
                        verbose_name="Model",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feature Flag History",
                "verbose_name_plural": "Feature Flag Histories",
                "db_table": "devops_featureflag_audithistory",
                "managed": True,
            },
            bases=("core.centurionaudit", models.Model),
        ),
        migrations.CreateModel(
            name="FeatureFlagCenturionModelNote",
            fields=[
                (
                    "centurionmodelnote_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.centurionmodelnote",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        help_text="Model this note belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="devops.featureflag",
                        verbose_name="Model",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feature Flag Note",
                "verbose_name_plural": "Feature Flag Notes",
                "db_table": "devops_featureflag_centurionmodelnote",
                "managed": True,
            },
            bases=("core.centurionmodelnote", models.Model),
        ),
    ]
