# Generated by Django 5.1.15 on 2026-02-09 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("devops", "0016_alter_checkin_organization_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FeatureFlagHistory",
        ),
        migrations.DeleteModel(
            name="FeatureFlagNotes",
        ),
        migrations.DeleteModel(
            name="GitGroupHistory",
        ),
        migrations.DeleteModel(
            name="GitGroupNotes",
        ),
        migrations.DeleteModel(
            name="GitHubHistory",
        ),
        migrations.DeleteModel(
            name="GitHubRepositoryNotes",
        ),
        migrations.DeleteModel(
            name="GitHubRepositoryTicket",
        ),
        migrations.DeleteModel(
            name="GitlabHistory",
        ),
        migrations.DeleteModel(
            name="GitLabRepositoryNotes",
        ),
        migrations.DeleteModel(
            name="GitLabRepositoryTicket",
        ),
    ]
