# Generated by Django 5.1.14 on 2025-11-19 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("devops", "0016_alter_checkin_organization_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GitHubRepositoryTicket",
        ),
        migrations.DeleteModel(
            name="GitLabRepositoryTicket",
        ),
    ]
