# Generated by Django 5.1.15 on 2025-12-09 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("devops", "0017_remove_gitlabrepositoryticket_model_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FeatureFlagHistory",
        ),
        migrations.DeleteModel(
            name="GitGroupHistory",
        ),
        migrations.DeleteModel(
            name="GitHubHistory",
        ),
        migrations.DeleteModel(
            name="GitlabHistory",
        ),
    ]
