# Generated by Django 5.1.9 on 2025-06-09 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_alter_ticketcommentcategory_parent_and_more"),
        ("devops", "0018_gitrepositoryaudithistory_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GitHubRepositoryAuditHistory",
            fields=[
                (
                    "centurionaudit_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.centurionaudit",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        help_text="Model this history belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="devops.githubrepository",
                        verbose_name="Model",
                    ),
                ),
            ],
            options={
                "verbose_name": "GitHub Repository History",
                "verbose_name_plural": "GitHub Repository Histories",
                "db_table": "devops_githubrepository_audithistory",
                "managed": True,
            },
            bases=("core.centurionaudit",),
        ),
        migrations.CreateModel(
            name="GitHubRepositoryCenturionModelNote",
            fields=[
                (
                    "centurionmodelnote_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.centurionmodelnote",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        help_text="Model this note belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="devops.githubrepository",
                        verbose_name="Model",
                    ),
                ),
            ],
            options={
                "verbose_name": "GitHub Repository Note",
                "verbose_name_plural": "GitHub Repository Notes",
                "db_table": "devops_githubrepository_centurionmodelnote",
                "managed": True,
            },
            bases=("core.centurionmodelnote",),
        )
    ]
