# Generated by Django 5.1.15 on 2025-12-09 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("devops", "0018_remove_gitgrouphistory_model_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FeatureFlagNotes",
        ),
        migrations.DeleteModel(
            name="GitGroupNotes",
        ),
        migrations.DeleteModel(
            name="GitHubRepositoryNotes",
        ),
        migrations.DeleteModel(
            name="GitLabRepositoryNotes",
        ),
    ]
