---

name: 'Mirror'


on:
  push:
    branches:
      - '**'
    tags:
      - '*'


jobs:


  gitlab-mirror:
    if: github.repository == 'nofusscomputing/centurion_erp'
    runs-on: ubuntu-latest
    steps:


      - name: clone
        shell: bash
        run: |

          git clone --mirror https://github.com/${{ github.repository }} repo;

          ls -la repo/


      - name: add remote
        shell: bash
        env:
          GIT_SYNC_URL: "https://${{ secrets.GITLAB_USERNAME_ROBOT }}:${{ secrets.GITLAB_TOKEN_ROBOT }}@gitlab.com/nofusscomputing/projects/centurion_erp.git"
        run: |

          cd repo;

          echo "**************************************** - git remote -v";

          git remote -v;

          echo "****************************************";

          git remote add destination $GIT_SYNC_URL;


      - name: push branches
        shell: bash
        run: |

          cd repo;

          echo "**************************************** - git branch";

          git branch;

          echo "****************************************";

          # git push destination --all --force;

          git push destination --mirror || true;


      # - name: push tags
      #   shell: bash
      #   run: |

      #     cd repo;

      #     echo "**************************************** - git tag";

      #     git tag;

      #     echo "****************************************";

      #     git push destination --tags --force;
